const base=()=>String(process.env.MASTER_API_URL||"").replace(/\/+$/,"" ).replace(/\/api$/i,"");
const timeoutMs=()=>Math.max(1000,Number(process.env.MASTER_API_TIMEOUT_MS||10000));
const getCacheSeconds=()=>Math.min(300,Math.max(0,Number(process.env.MASTER_API_CACHE_SECONDS||30)));
type MasterRole="billing"|"deployer";
const token=(role:MasterRole="billing")=>String(role==="deployer"?(process.env.DEPLOYER_API_TOKEN||process.env.BILLING_API_TOKEN):(process.env.BILLING_API_TOKEN||process.env.DEPLOYER_API_TOKEN||"")).trim();
function requireConfig(role:MasterRole="billing"){const url=base(),value=token(role);if(!url)throw new Error("MASTER_API_URL is not configured");if(!value)throw new Error("License Master API token is not configured");return {url,token:value};}
export async function masterRequest(path:string,init:RequestInit={},role:MasterRole="billing"){const cfg=requireConfig(role);const headers=new Headers(init.headers);headers.set("authorization",`Bearer ${cfg.token}`);if(!headers.has("content-type")&&init.body)headers.set("content-type","application/json");const controller=init.signal?null:new AbortController();const timer=controller?setTimeout(()=>controller.abort(),timeoutMs()):null;const method=String(init.method||"GET").toUpperCase();const cacheSeconds=getCacheSeconds();const fetchInit:any={...init,headers,signal:init.signal||controller?.signal};if(method==="GET"&&cacheSeconds>0)fetchInit.next={revalidate:cacheSeconds};else fetchInit.cache="no-store";try{const response=await fetch(`${cfg.url}${path}`,fetchInit);const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={error:text||"License Master returned an invalid response"}}if(!response.ok)throw Object.assign(new Error(data?.error||`License Master request failed (${response.status})`),{status:response.status,code:data?.code});return data;}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new Error(`License Master request timed out after ${timeoutMs()}ms`);throw error;}finally{if(timer)clearTimeout(timer);}}
export async function masterBinaryRequest(path:string,init:RequestInit={},role:MasterRole="billing"):Promise<{bytes:Buffer;contentType:string;headers:Headers}>{const cfg=requireConfig(role);const headers=new Headers(init.headers);headers.set("authorization",`Bearer ${cfg.token}`);const controller=init.signal?null:new AbortController();const timer=controller?setTimeout(()=>controller.abort(),timeoutMs()):null;try{const response=await fetch(`${cfg.url}${path}`,{...init,headers,cache:"no-store",signal:init.signal||controller?.signal});if(!response.ok){const text=await response.text();let message=text||`License Master request failed (${response.status})`;try{message=JSON.parse(text)?.error||message}catch{}throw Object.assign(new Error(message),{status:response.status});}return {bytes:Buffer.from(await response.arrayBuffer()),contentType:response.headers.get("content-type")||"application/octet-stream",headers:response.headers};}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new Error(`License Master request timed out after ${timeoutMs()}ms`);throw error;}finally{if(timer)clearTimeout(timer);}}
export const masterHealth=()=>masterRequest("/api/health",{method:"GET"});
export const masterRevision=()=>masterRequest("/api/health",{method:"GET"});
export const masterProducts=()=>masterRequest("/api/products",{method:"GET"});
export const masterLicenses=()=>masterRequest("/api/licenses",{method:"GET"});
export const masterDeployments=()=>masterRequest("/api/deployments",{method:"GET"},"deployer");
export const masterReleases=(product="orbitfs_base",channel="stable",type="base")=>masterRequest(`/api/releases?product=${encodeURIComponent(product)}&channel=${encodeURIComponent(channel)}&type=${encodeURIComponent(type)}`,{method:"GET"});
export async function masterLicenseValidate(input:any){return masterRequest("/api/license/validate",{method:"POST",body:JSON.stringify({license_key:input.licenseKey||input.license_key,product:input.product||input.product_code||"orbitfs_base",installation_id:input.installationId||input.installation_id,product_version:input.appVersion||input.product_version,metadata:input.metadata||{}})});}
export const masterValidate=masterLicenseValidate;
export async function masterIssue(input:any){return masterRequest("/api/license/issue",{method:"POST",body:JSON.stringify({product:input.product||input.product_code||input.productCode,customer_external_id:input.customer_external_id,external_reference:input.external_reference,expires_at:input.expires_at,metadata:input.metadata||{}})},"billing");}
export async function masterControl(id:string,input:any){return masterRequest(`/api/license/${encodeURIComponent(id)}/control`,{method:"POST",body:JSON.stringify(input)},"billing");}
export async function masterCreateRelease(input:any){const component=String(input.component||"").trim();const product=String(input.product||input.product_code||component||"orbitfs_base");return masterRequest("/api/releases",{method:"POST",body:JSON.stringify({...input,product,release_type:input.release_type||"base",artifact_url:input.artifact_url||null})},"billing");}
export async function masterUpdateRelease(id:string,input:any){return masterRequest(`/api/releases/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)},"billing");}
export async function masterPublishRelease(id:string){return masterRequest(`/api/releases/${encodeURIComponent(id)}`,{method:"POST",body:JSON.stringify({action:"publish"})},"billing");}
export async function masterValidateRelease(id:string){return masterRequest(`/api/releases/${encodeURIComponent(id)}`,{method:"POST",body:JSON.stringify({action:"approve"})},"billing");}
export async function masterControlRelease(id:string,status:string){const action=status==="paused"?"disable":status==="withdrawn"?"withdraw":status;return masterRequest(`/api/releases/${encodeURIComponent(id)}`,{method:"POST",body:JSON.stringify({action})},"billing");}
export async function masterDownloadReleaseArtifact(id:string){return masterBinaryRequest(`/api/releases/${encodeURIComponent(id)}/artifact`,{method:"GET"},"billing");}
export async function masterUploadReleaseArtifact(id:string,bytes:Buffer,contentType="application/octet-stream"){return masterRequest(`/api/releases/${encodeURIComponent(id)}/artifact`,{method:"POST",headers:{"content-type":contentType,"x-artifact-name":`orbitfs-release-${id}.bin`},body:bytes as any},"billing");}
export async function masterExecuteDeployment(input:any){return masterRequest("/api/deployments",{method:"POST",body:JSON.stringify(input)},"deployer");}
export async function masterSyncDeployment(input:any){const deploymentId=String(input.vercelDeploymentId||input.vercel_deployment_id||input.deploymentId||input.deployment_id||"").trim();if(!deploymentId)throw new Error("vercelDeploymentId is required");return masterRequest("/api/deployments/sync",{method:"POST",body:JSON.stringify(input)},"deployer");}
export const licensingAuthority="orbitfs-license-master-v2";
