const base=()=>String(process.env.MASTER_API_URL||"").replace(/\/$/,"");
const timeoutMs=()=>Math.max(1000,Number(process.env.MASTER_API_TIMEOUT_MS||10000));
type MasterRole="billing"|"deployer";
const token=(role:MasterRole="billing")=>String(role==="deployer"?process.env.DEPLOYER_API_TOKEN:process.env.BILLING_API_TOKEN||"");
function requireConfig(role:MasterRole="billing"){const url=base(),value=token(role);if(!url)throw new Error("MASTER_API_URL is not configured");if(!value)throw new Error(`${role==="deployer"?"DEPLOYER_API_TOKEN":"BILLING_API_TOKEN"} is not configured`);return {url,token:value};}
export async function masterRequest(path:string,init:RequestInit={},role:MasterRole="billing"){const cfg=requireConfig(role);const headers=new Headers(init.headers);headers.set("authorization",`Bearer ${cfg.token}`);if(!headers.has("content-type")&&init.body)headers.set("content-type","application/json");const controller=init.signal?null:new AbortController();const timer=controller?setTimeout(()=>controller.abort(),timeoutMs()):null;try{const response=await fetch(`${cfg.url}${path}`,{...init,headers,cache:"no-store",signal:init.signal||controller?.signal});const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={error:text||"Master API returned an invalid response"}}if(!response.ok)throw Object.assign(new Error(data?.error||`Master API request failed (${response.status})`),{status:response.status,code:data?.code});return data;}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new Error(`Master API request timed out after ${timeoutMs()}ms`);throw error;}finally{if(timer)clearTimeout(timer);}}
export async function masterBinaryRequest(path:string,init:RequestInit={},role:MasterRole="billing"):Promise<{bytes:Buffer;contentType:string;headers:Headers}>{const cfg=requireConfig(role);const headers=new Headers(init.headers);headers.set("authorization",`Bearer ${cfg.token}`);const controller=init.signal?null:new AbortController();const timer=controller?setTimeout(()=>controller.abort(),timeoutMs()):null;try{const response=await fetch(`${cfg.url}${path}`,{...init,headers,cache:"no-store",signal:init.signal||controller?.signal});if(!response.ok){const text=await response.text();let message=text||`Master API request failed (${response.status})`;try{message=JSON.parse(text)?.error||message}catch{}throw Object.assign(new Error(message),{status:response.status});}return {bytes:Buffer.from(await response.arrayBuffer()),contentType:response.headers.get("content-type")||"application/octet-stream",headers:response.headers};}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new Error(`Master API request timed out after ${timeoutMs()}ms`);throw error;}finally{if(timer)clearTimeout(timer);}}
export const masterHealth=()=>masterRequest("/api/health",{method:"GET"});
export const masterProducts=()=>masterRequest("/api/products",{method:"GET"});
export const masterSettings=()=>masterRequest("/api/settings",{method:"GET"});
export const masterLicenses=()=>masterRequest("/api/licenses",{method:"GET"});
export const masterInstallations=()=>masterRequest("/api/installations",{method:"GET"});
export const masterDeployments=()=>masterRequest("/api/deployments",{method:"GET"},"deployer");
export const masterReleases=()=>masterRequest("/api/releases",{method:"GET"});
export const masterRevision=()=>masterRequest("/api/license/revision",{method:"GET"});
export const masterPublicKey=()=>masterRequest("/api/license/public-key",{method:"GET"});
export async function masterLicenseValidate(input:any){return masterRequest("/api/license/validate",{method:"POST",body:JSON.stringify({licenseKey:input.licenseKey||input.license_key,installationId:input.installationId||input.installation_id,components:input.components||null,activate:!!input.activate,deviceName:input.deviceName||null,platform:input.platform||null,appVersion:input.appVersion||null})});}
export const masterValidate=masterLicenseValidate;
export async function masterIssue(input:any){return masterRequest("/api/license/issue",{method:"POST",body:JSON.stringify(input)},"billing");}
export async function masterControl(id:string,input:any){return masterRequest(`/api/license/${encodeURIComponent(id)}/control`,{method:"POST",body:JSON.stringify(input)},"billing");}
export async function masterCreateRelease(input:any){return masterRequest("/api/releases",{method:"POST",body:JSON.stringify(input)},"billing");}
export async function masterPublishRelease(id:string){return masterRequest(`/api/releases/${encodeURIComponent(id)}/publish`,{method:"POST"},"billing");}
export async function masterValidateRelease(id:string){return masterRequest(`/api/releases/${encodeURIComponent(id)}/validate`,{method:"POST"},"billing");}
export async function masterControlRelease(id:string,status:string){return masterRequest(`/api/releases/${encodeURIComponent(id)}/control`,{method:"POST",body:JSON.stringify({action:status})},"billing");}
export async function masterUploadReleaseArtifact(id:string,bytes:Buffer,contentType="application/octet-stream"){return masterRequest(`/api/releases/${encodeURIComponent(id)}/artifact`,{method:"POST",headers:{"content-type":contentType,"x-artifact-sha256":(await import("node:crypto")).createHash("sha256").update(bytes).digest("hex")},body:new Uint8Array(bytes)},"billing");}
export async function masterDownloadReleaseArtifact(id:string){return masterBinaryRequest(`/api/releases/${encodeURIComponent(id)}/artifact`,{method:"GET"},"billing");}
export async function masterExecuteDeployment(input:any){return masterRequest("/api/deployments/execute",{method:"POST",body:JSON.stringify(input)},"deployer");}
export async function masterSyncDeployment(input:any){return masterRequest("/api/deployments/sync",{method:"POST",body:JSON.stringify(input)},"deployer");}
export async function masterCaptureRelease(kind:"base"|"update",input:any={}){return masterRequest(`/api/release-capture`,{method:"POST",body:JSON.stringify({kind,...input})},"billing");}
export async function masterUpdateRelease(id:string,input:any){return masterRequest(`/api/release-control?id=${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)},"billing");}
export const masterLatestRelease=()=>masterRequest("/api/releases/latest",{method:"GET"});
export async function masterReleaseHandoff(action:string,id?:string,body:any={}){return masterRequest(`/api/release-handoff?action=${encodeURIComponent(action)}${id?`&id=${encodeURIComponent(id)}`:""}`,{method:action==="drafts"?"GET":"POST",body:action==="drafts"?undefined:JSON.stringify(body)},"billing");}
export const licensingAuthority="orbitfs-license-master-v2";
