const MASTER_ORIGIN=()=>String(process.env.MASTER_API_URL||"https://incendiarynetworks.cc").trim().replace(/\/+$/,'').replace(/\/api\/v1$/i,'').replace(/\/api$/i,'');
const timeoutMs=()=>Math.max(1000,Number(process.env.MASTER_API_TIMEOUT_MS||10000));
const getCacheSeconds=()=>Math.min(300,Math.max(0,Number(process.env.MASTER_API_CACHE_SECONDS||30)));
type MasterRole="billing"|"deployer";
const token=(role:MasterRole="billing")=>String(role==="deployer"?(process.env.DEPLOYER_API_TOKEN||process.env.BILLING_API_TOKEN||process.env.INTEGRATION_API_TOKEN):(process.env.BILLING_API_TOKEN||process.env.INTEGRATION_API_TOKEN||"")).trim();
function requireConfig(role:MasterRole="billing"){const url=MASTER_ORIGIN(),value=token(role);if(!value)throw new Error("License Master API token is not configured (set BILLING_API_TOKEN or INTEGRATION_API_TOKEN)");return {url,value};}
function masterPath(path:string){return path.startsWith("/api/v1/")?path:path.startsWith("/api/")?`/api/v1${path.slice(4)}`:`/api/v1/${path.replace(/^\/+/,"")}`;}
async function fetchWithTimeout(url:string,init:RequestInit,role:MasterRole="billing"){const cfg=requireConfig(role);const headers=new Headers(init.headers);headers.set("authorization",`Bearer ${cfg.value}`);const controller=init.signal?null:new AbortController();const timer=controller?setTimeout(()=>controller.abort(),timeoutMs()):null;try{return await fetch(url,{...init,headers,signal:init.signal||controller?.signal});}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new Error(`License Master request timed out after ${timeoutMs()}ms`);throw error;}finally{if(timer)clearTimeout(timer);}}
export async function masterRequest(path:string,init:RequestInit={},role:MasterRole="billing"){const headers=new Headers(init.headers);if(!headers.has("content-type")&&init.body)headers.set("content-type","application/json");const method=String(init.method||"GET").toUpperCase();const fetchInit:any={...init,headers};if(method==="GET"&&getCacheSeconds()>0)fetchInit.next={revalidate:getCacheSeconds()};else fetchInit.cache="no-store";const cfg=requireConfig(role);const response=await fetchWithTimeout(`${cfg.url}${masterPath(path)}`,fetchInit,role);const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={error:text||"License Master returned an invalid response"}}if(!response.ok)throw Object.assign(new Error(data?.error||`License Master request failed (${response.status})`),{status:response.status,code:data?.code});return data;}
export const masterHealth=()=>masterRequest("/api/health",{method:"GET"});
export const masterRevision=()=>masterRequest("/api/license/revision",{method:"GET"});
export const masterProducts=()=>masterRequest("/api/products",{method:"GET"});
export const masterLicenses=()=>masterRequest("/api/licenses",{method:"GET"});
export const masterDeployments=()=>masterRequest("/api/deployments",{method:"GET"},"deployer");
export const masterReleases=(product="orbitfs_base",channel="stable",type="base")=>masterRequest(`/api/releases?product=${encodeURIComponent(product)}&channel=${encodeURIComponent(channel)}&type=${encodeURIComponent(type)}`,{method:"GET"});
export async function masterLicenseValidate(input:any){return masterRequest("/api/license/validate",{method:"POST",body:JSON.stringify({licenseKey:input.licenseKey||input.license_key,installationId:input.installationId||input.installation_id,product:input.product||input.product_code||"orbitfs_base",productVersion:input.productVersion||input.product_version||input.appVersion||input.product_version,metadata:input.metadata||{}})});}
export const masterValidate=masterLicenseValidate;
export async function masterIssue(input:any){return masterRequest("/api/license/issue",{method:"POST",headers:{"x-orbitfs-order-ref":String(input.external_reference||input.orderRef||"")},body:JSON.stringify({orderRef:input.external_reference||input.orderRef,customerRef:input.customer_external_id||input.customerRef,productCode:input.product||input.product_code||input.productCode||"orbitfs_base",expiresAt:input.expires_at||input.expiresAt||null,components:input.components||{},maxInstallations:input.max_installations||input.maxInstallations||1,metadata:input.metadata||{},notes:input.notes||null,actorRef:input.actorRef||"billing_store"})},"billing");}
export async function masterControl(id:string,input:any){const action=String(input?.action||"").toLowerCase();return masterRequest(`/api/license/${encodeURIComponent(id)}/control`,{method:"POST",body:JSON.stringify({...input,action,actorRef:input?.actorRef||"billing_store"})},"billing");}
export async function masterCreateRelease(input:any){return masterRequest("/api/releases",{method:"POST",body:JSON.stringify({...input,product:input.product||input.product_code||"orbitfs_base",release_type:input.release_type||"base"})},"billing");}
export async function masterUpdateRelease(id:string,input:any){return masterRequest(`/api/releases/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(input)},"billing");}
export async function masterPublishRelease(id:string){return masterRequest(`/api/releases/${encodeURIComponent(id)}/publish`,{method:"POST"},"billing");}
export async function masterValidateRelease(id:string){return masterRequest(`/api/releases/${encodeURIComponent(id)}/validate`,{method:"POST"},"billing");}
export async function masterControlRelease(id:string,status:string){const action=status==="paused"?"pause":status==="withdrawn"?"withdraw":status;return masterRequest(`/api/releases/${encodeURIComponent(id)}/control`,{method:"POST",body:JSON.stringify({action})},"billing");}
export async function masterDownloadReleaseArtifact(id:string){const cfg=requireConfig("deployer");const response=await fetchWithTimeout(`${cfg.url}${masterPath(`/api/releases/${encodeURIComponent(id)}/artifact`)}`,{method:"GET",cache:"no-store"},"deployer");if(!response.ok){const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{}throw Object.assign(new Error(data?.error||`License Master artifact download failed (${response.status})`),{status:response.status,code:data?.code});}return {bytes:Buffer.from(await response.arrayBuffer()),contentType:response.headers.get("content-type")||"application/octet-stream",contentDisposition:response.headers.get("content-disposition")||null};}
export async function masterUploadReleaseArtifact(id:string,bytes:Buffer|string,contentType="application/octet-stream"){return masterRequest(`/api/releases/${encodeURIComponent(id)}/artifact`,{method:"POST",headers:{"content-type":contentType},body:bytes as any},"deployer");}
export async function masterExecuteDeployment(input:any){return masterRequest("/api/deployments/execute",{method:"POST",body:JSON.stringify(input)},"deployer");}
export async function masterSyncDeployment(input:any){return masterRequest("/api/deployments/sync",{method:"POST",body:JSON.stringify(input)},"deployer");}
export const licensingAuthority="orbitfs-license-master-v2";
