"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";
import "../licensing/licensing.css";

const RELEASE_SOURCES:Record<string,string>=Object.freeze({
 orbitfs_base:"https://github.com/lucaskerim123/V1-vercel-base/tree/base-release",
 orbitfs_mcp:"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates",
 orbitfs_apex:"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates",
 orbitfs_studio:"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates"
});
const source=(r:any)=>RELEASE_SOURCES[String(r?.component||"")]||"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates";
const rolloutLabel=(v:string)=>v==="public"?"Customer visible":v==="beta"?"Beta customers":"Internal only";
export default function AdminReleaseManager(){
 const sb=useMemo(()=>createClient(),[]),[releases,setReleases]=useState<any[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[busy,setBusy]=useState(""),[drafts,setDrafts]=useState<Record<string,any>>({});
 async function request(path:string,method="GET",body?:any){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw Error("Administrator session expired.");const r=await fetch(`/api/admin/license-master?path=${encodeURIComponent(path)}`,{method,headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`License Master returned ${r.status}`);return j}
 async function load(){setLoading(true);try{const j=await request("/api/v1/releases");const rows=(j.releases||[]).filter((r:any)=>["orbitfs_base","orbitfs_mcp","orbitfs_apex","orbitfs_studio"].includes(String(r.component||""))).sort((a:any,b:any)=>String(b.updated_at||b.updatedAt||b.created_at||b.createdAt).localeCompare(String(a.updated_at||a.updatedAt||a.created_at||a.createdAt)));setReleases(rows);setDrafts(Object.fromEntries(rows.map((r:any)=>[r.id,{rollout:r.rollout||r.manifest?.rollout||"internal",customer_notes:r.customer_notes||r.manifest?.customerNotes||"",severity:r.severity||r.manifest?.severity||"normal",required:r.required===true||r.manifest?.required===true}])));setMsg("")}catch(e:any){setMsg(e.message||"Could not reach License Master releases.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function update(id:string){const p=drafts[id]||{};setBusy(id+":update");try{await request(`/api/release-control?id=${encodeURIComponent(id)}`,"PATCH",p);setMsg("Final release visibility/settings saved to License Master.");await load()}catch(e:any){setMsg(e.message||"Could not save release settings.")}finally{setBusy("")}}
 async function action(id:string,op:string){if(!confirm(`${op} release ${id}?`))return;setBusy(id+op);try{await request(`/api/v1/releases/${encodeURIComponent(id)}/${op}`,"POST",{});setMsg(`Release ${op} completed.`);await load()}catch(e:any){setMsg(e.message||`Release ${op} failed.`)}finally{setBusy("")}}
 return <main className="lmPage">
  <div className="lmHero"><div><div className="lmEyebrow">ORBITFS · RELEASE CONTROL PLANE</div><h1>Releases</h1><p>License Master captures source releases and owns release authority. Billing Store receives the drafts, applies final customer visibility/settings, then publishes the authoritative release consumed by My OrbitFS.</p></div><div className="lmHeroActions"><Link href="/admin/orbitfs">← My OrbitFS</Link><Link href="/admin/orbitfs/base-deploy">Deployment</Link><button onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh from License Master"}</button></div></div>
  <section className="lmCard"><div className="lmKicker">AUTHORITATIVE PIPELINE</div><div className="lmRuntimeList"><div><b>1 · License Master</b><span>Captures Base only from <a href="https://github.com/lucaskerim123/V1-vercel-base/tree/base-release" target="_blank" rel="noreferrer">https://github.com/lucaskerim123/V1-vercel-base/tree/base-release</a> and updates only from <a href="https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates" target="_blank" rel="noreferrer">https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates</a>.</span></div><div><b>2 · Billing Store</b><span>Receives Master drafts and controls final rollout, customer notes, severity and required-update settings.</span></div><div><b>3 · Publish</b><span>Publishing happens through License Master; My OrbitFS only exposes published releases eligible for the customer's audience and entitlement.</span></div><div><b>4 · Deployment</b><span>My OrbitFS deploys or updates the customer's existing Vercel installation through the deployment control plane.</span></div></div></section>
  <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">MASTER RELEASES</div><h2>Drafts, candidates and published releases</h2></div></header>{loading?<div className="lmLoading">Loading License Master releases…</div>:releases.length?<div className="lmReleaseList">{releases.map((r:any)=>{const p=drafts[r.id]||{};const status=String(r.status||"draft");return <div className="lmRelease" key={r.id}><div style={{minWidth:0,flex:1}}><b>{r.version||r.id}</b><small>{r.component} · {r.channel} · <a href={source(r)} target="_blank" rel="noreferrer">{source(r)}</a> · {status}</small><p style={{whiteSpace:"pre-wrap"}}>{r.changelog||r.release_notes||r.description||"No changelog"}</p><small>Source commit: {r.source_commit||r.manifest?.sourceCommit||"not captured"}</small></div><div style={{display:"grid",gap:7,minWidth:210}}><label>Visibility<select value={p.rollout||"internal"} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,rollout:e.target.value}}))}><option value="internal">Internal only</option><option value="beta">Beta customers</option><option value="public">Customer visible</option></select></label><label>Severity<select value={p.severity||"normal"} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,severity:e.target.value}}))}><option value="normal">Normal</option><option value="important">Important</option><option value="critical">Critical</option></select></label><label>Customer notes<textarea rows={3} value={p.customer_notes||""} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,customer_notes:e.target.value}}))}/></label><label><input type="checkbox" checked={p.required===true} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,required:e.target.checked}}))}/> Required update</label><button disabled={!!busy} onClick={()=>void update(r.id)}>{busy===r.id+":update"?"Saving…":"Save final settings"}</button></div><div className="actions">{status==="draft"&&<button disabled={!!busy} onClick={()=>void action(r.id,"validate")}>Validate</button>}{status==="validated"&&<button className="primary" disabled={!!busy||p.rollout==="internal"} onClick={()=>void action(r.id,"publish")}>Publish</button>}{(status==="published"||status==="validated")&&<button disabled={!!busy} onClick={()=>void action(r.id,"pause")}>Pause</button>}{status!=="withdrawn"&&<button className="danger" disabled={!!busy} onClick={()=>void action(r.id,"withdraw")}>Withdraw</button>}</div></div>})}</div>:<div className="lmEmpty">No releases are currently registered in License Master.</div>}{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</section>
 </main>
}
