"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";
import "../licensing/licensing.css";

const RELEASE_SOURCES:Record<string,string>=Object.freeze({orbitfs_base:"https://github.com/lucaskerim123/V1-vercel-base/tree/base-release",orbitfs_mcp:"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates",orbitfs_apex:"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates",orbitfs_studio:"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates"});
const source=(r:any)=>RELEASE_SOURCES[String(r?.component||"")]||"https://github.com/lucaskerim123/V1-vercel-engine/tree/release-updates";
const statusLabel=(s:string)=>({draft:"Draft",validated:"Technically validated",ready_for_store:"Ready for Store",published:"Published",paused:"Paused",withdrawn:"Withdrawn"}[s]||s.replaceAll("_"," "));
export default function AdminReleaseManager(){
 const sb=useMemo(()=>createClient(),[]),[releases,setReleases]=useState<any[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[busy,setBusy]=useState(""),[drafts,setDrafts]=useState<Record<string,any>>({}),[automation,setAutomation]=useState<any>();
 async function request(path:string,method="GET",body?:any){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw Error("Administrator session expired.");const r=await fetch(`/api/admin/license-master?path=${encodeURIComponent(path)}`,{method,headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`License Master returned ${r.status}`);return j}
 async function load(){setLoading(true);setMsg("");const [masterResult,handoffResult]=await Promise.allSettled([request("/api/releases"),request("/api/release-handoff?action=drafts")]);if(masterResult.status!=="fulfilled"){setReleases([]);setLoading(false);setMsg(masterResult.reason?.message||"Could not reach License Master release control plane.");return}const master=masterResult.value;const d=handoffResult.status==="fulfilled"?handoffResult.value:{releases:[]};const rows=(master.releases||[]).filter((r:any)=>["orbitfs_base","orbitfs_mcp","orbitfs_apex","orbitfs_studio"].includes(String(r.component||""))).sort((a:any,b:any)=>String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at)));const handoff=Object.fromEntries((d.releases||[]).map((r:any)=>[r.id,r]));setReleases(rows.map((r:any)=>({...r,handoff:handoff[r.id]||null})));setDrafts(Object.fromEntries(rows.map((r:any)=>[r.id,{rollout:r.rollout||r.manifest?.rollout||"internal",customer_notes:r.customer_notes||r.manifest?.customerNotes||"",severity:r.severity||r.manifest?.severity||"normal",required:r.required===true||r.manifest?.required===true}])));try{setAutomation((await request("/api/release-automation-settings")).settings)}catch{}if(handoffResult.status!=="fulfilled")setMsg("Release list loaded. Store handoff data is temporarily unavailable.");setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function update(id:string){const p=drafts[id]||{};setBusy(id+":update");try{await request(`/api/release-control?id=${encodeURIComponent(id)}`,"PATCH",p);setMsg("Billing Store publication settings saved.");await load()}catch(e:any){setMsg(e.message||"Could not save release settings.")}finally{setBusy("")}}
 async function handoff(id:string){if(!confirm("Finalize this technically validated release and send the final draft to Billing Store?"))return;setBusy(id+":handoff");try{await request(`/api/release-handoff?action=finalize&id=${encodeURIComponent(id)}`,"POST",{});setMsg("Final release draft handed off from License Master to Billing Store.");await load()}catch(e:any){setMsg(e.message||"Could not finalize the release.")}finally{setBusy("")}}
 async function publish(id:string){const p=drafts[id]||{};if(p.rollout==="internal")return setMsg("Set the Store visibility before publishing.");if(!confirm("Publish this final release to eligible customers?"))return;setBusy(id+":publish");try{await request(`/api/release-handoff?action=publish&id=${encodeURIComponent(id)}`,"POST",{});setMsg("Release is now customer-visible through Billing Store.");await load()}catch(e:any){setMsg(e.message||"Could not publish the release.")}finally{setBusy("")}}
 async function retry(id:string){setBusy(id+":retry");try{await request(`/api/release-handoff?action=retry&id=${encodeURIComponent(id)}`,"POST",{});setMsg("Billing Store handoff retry completed.");await load()}catch(e:any){setMsg(e.message||"Could not retry the Store handoff.")}finally{setBusy("")}}
 async function control(id:string,action:string){if(!confirm(`${action} release ${id}?`))return;setBusy(id+action);try{await request(`/api/releases/${encodeURIComponent(id)}/${action}`,"POST",{});setMsg(`Release ${action} completed.`);await load()}catch(e:any){setMsg(e.message||`Release ${action} failed.`)}finally{setBusy("")}}
 return <main className="lmPage">
  <div className="lmHero"><div><div className="lmEyebrow">ORBITFS · BILLING STORE</div><h1>Release & Deployment Control</h1><p>License Master does the technical work. Billing Store receives the final draft, decides customer visibility, and publishes it to the Store and My OrbitFS.</p></div><div className="lmHeroActions"><Link href="/admin/orbitfs">← My OrbitFS</Link><Link href="/admin/orbitfs/base-deploy">Base deployment</Link><Link href="/admin/orbitfs/update-release-deployer">Update deployer</Link><button onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div></div>
  <section className="lmCard"><div className="lmKicker">PUBLICATION GATE</div><div className="lmRuntimeList"><div><b>1 · License Master</b><span>Captures source, builds, validates SemVer, packages and prepares the technical release.</span></div><div><b>2 · Final draft</b><span><code>ready_for_store</code> means Master has finished its work. The draft is now owned by Billing Store for publication.</span></div><div><b>3 · Billing Store</b><span>Set customer visibility, severity, required-update messaging and customer notes here.</span></div><div><b>4 · Customer</b><span>Only <code>published</code> releases appear as customer-available releases in My OrbitFS.</span></div></div></section>
  {automation&&<section className="lmCard" style={{marginTop:14}}><div className="lmKicker">AUTOMATION</div><div className="lmRuntimeList"><div><b>Global release automation</b><span>{automation.release_automation_enabled?"Enabled":"Off"}</span></div><div><b>Base auto-finalization</b><span>{automation.auto_finalize_base?"Enabled":"Off"}</span></div><div><b>Update auto-finalization</b><span>{automation.auto_finalize_updates?"Enabled":"Off"}</span></div></div><p className="muted" style={{marginTop:12}}>Automation may prepare and hand off a release when enabled. It does not bypass this Store publication gate.</p></section>}
  <section className="lmCard" style={{marginTop:14}}><header><div><div className="lmKicker">RELEASE QUEUE</div><h2>Base and Update releases</h2></div></header>{loading?<div className="lmLoading">Loading release queue…</div>:releases.length?<div className="lmReleaseList">{releases.map((r:any)=>{const p=drafts[r.id]||{};const status=String(r.status||"draft"),delivery=r.handoff;return <div className="lmRelease" key={r.id}><div style={{minWidth:0,flex:1}}><b>{r.version||r.id}</b><small>{r.component} · {r.channel} · <strong>{statusLabel(status)}</strong></small><p style={{whiteSpace:"pre-wrap"}}>{r.changelog||r.release_notes||r.description||"No changelog"}</p><small>Source: <a href={source(r)} target="_blank" rel="noreferrer">{source(r)}</a></small><small>Commit: {r.source_commit||r.manifest?.sourceCommit||"not captured"}</small>{delivery&&<small>Store delivery: {delivery.deliveryStatus||"pending"}{delivery.deliveryError?` · ${delivery.deliveryError}`:""}</small>}</div><div style={{display:"grid",gap:7,minWidth:230}}><label>Customer visibility<select value={p.rollout||"internal"} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,rollout:e.target.value}}))}><option value="internal">Internal only</option><option value="beta">Beta customers</option><option value="public">Customer visible</option></select></label><label>Severity<select value={p.severity||"normal"} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,severity:e.target.value}}))}><option value="normal">Normal</option><option value="important">Important</option><option value="critical">Critical</option></select></label><label>Customer notes<textarea rows={3} value={p.customer_notes||""} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,customer_notes:e.target.value}}))}/></label><label><input type="checkbox" checked={p.required===true} onChange={e=>setDrafts(x=>({...x,[r.id]:{...p,required:e.target.checked}}))}/> Required update</label><button disabled={!!busy} onClick={()=>void update(r.id)}>Save Store settings</button></div><div className="actions">{status==="validated"&&<button className="primary" disabled={!!busy} onClick={()=>void handoff(r.id)}>Send final draft to Store</button>}{status==="ready_for_store"&&<><button className="primary" disabled={!!busy||p.rollout==="internal"} onClick={()=>void publish(r.id)}>Publish to customers</button><button disabled={!!busy} onClick={()=>void retry(r.id)}>Retry handoff</button></>}{(status==="published"||status==="ready_for_store")&&<button disabled={!!busy} onClick={()=>void control(r.id,"pause")}>Pause</button>}{status!=="withdrawn"&&<button className="danger" disabled={!!busy} onClick={()=>void control(r.id,"withdraw")}>Withdraw</button>}</div></div>})}</div>:<div className="lmEmpty">No OrbitFS releases are currently registered in License Master.</div>}{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</section>
 </main>
}
