"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

const pretty=(v:any)=>String(v||"waiting").replaceAll("_"," ");
export default function OrbitFSDeploymentCenter(){
  const sb=useMemo(()=>createClient(),[]);const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
  async function auth():Promise<HeadersInit>{const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}};
  async function load(){setLoading(true);setMsg("");try{const r=await fetch("/api/orbitfs/status",{headers:await auth(),cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Could not load deployment status (${r.status})`);setData(j)}catch(e:any){setMsg(e?.message||"Could not load deployment status.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const binding=(data?.bindings||[])[0],install=(data?.installations||[])[0],latestBase=data?.latestBase?.version,latestUpdate=data?.latestUpdate?.version,baseRelease=data?.latestBase,updateRelease=data?.latestUpdate,updateAvailable=!!install?.release_version&&!!latestUpdate&&install.release_version!==latestUpdate;
  async function deploy(action:"deploy"|"update"|"rollback"|"redeploy",version?:string,releaseId?:string){if(!install)return setMsg("Open setup first to create your OrbitFS installation.");if(action==="rollback"&&!version){version=prompt("Version to roll back to:",install.previous_release_version||"")||undefined;if(!version)return}const target=releaseId&&action==="deploy"?`release:${releaseId}`:action==="update"&&version&&!version.startsWith("update:")?`update:${version}`:version;if(!confirm(`${action} OrbitFS${version?` to ${version}`:""}?`))return;setBusy(action);try{const r=await fetch(`/api/orbitfs/installations/${install.id}/deploy`,{method:"POST",headers:{...(await auth()),"content-type":"application/json"},body:JSON.stringify({action,version:target})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`${action} failed.`);setMsg(j.message||`OrbitFS ${action} started.`);await load()}catch(e:any){setMsg(e?.message||`${action} failed.`)}finally{setBusy("")}}
  if(loading)return <main className="portalOverviewV2"><section className="panel"><h2>Loading OrbitFS…</h2></section></main>;
  return <main className="portalOverviewV2"><header className="portalOverviewHero"><div><p className="eyebrow">ORBITFS</p><h1>My OrbitFS</h1><p className="muted">Deploy the latest Base release to your Vercel account and manage updates for this installation.</p></div><Link className="buttonlink" href="/portal/orbitfs">Setup</Link></header>{!data?<section className="panel"><h2>Deployment unavailable</h2><p className="muted">{msg}</p><button onClick={()=>void load()}>Retry</button></section>:<>
    <section className="panel"><div className="panelTitle"><div><p className="eyebrow">BASE DEPLOYMENT</p><h2>{install?.vercel_project_name||"OrbitFS Base"}</h2><p className="muted">The published release, approval state, artifact and checksum shown here come from License Master.</p></div><span className={`state ${install?.state==="ready"?"ready":"waiting"}`}>{pretty(install?.state||"not deployed")}</span></div><div className="listrow"><div><b>Available Base release</b><span>{latestBase?`v${latestBase} · ${baseRelease?.channel||install?.release_channel||"stable"} · ${baseRelease?.status||"published"}`:"No published Base release available"}</span></div><button disabled={!!busy||!baseRelease} onClick={()=>void deploy(install?.release_version?"redeploy":"deploy",latestBase,baseRelease?.releaseId||baseRelease?.id)}>{busy?"Working…":install?.release_version?"Redeploy this Base release":"Deploy Base"}</button></div><div className="listrow"><div><b>Installed Base</b><span>{install?.release_version||"Not deployed"}{install?.release_channel?` · ${install.release_channel}`:""}{install?.release_id?` · ${String(install.release_id).slice(0,12)}…`:""}</span></div><span className="mono">{install?.release_sha256||"No deployment checksum"}</span></div>{baseRelease&&<div style={{display:"grid",gap:8,marginTop:14}}><div className="listrow"><div><b>{baseRelease.title||`OrbitFS Base ${latestBase}`}</b><span>{baseRelease.description||"Published OrbitFS Base deployment"}</span></div><span>{baseRelease.manifest?.components?.length?`${baseRelease.manifest.components.length} components`:"Manifest available"}</span></div><div className="listrow"><div><b>Source</b><span>{baseRelease.source_repo||"—"} @ {baseRelease.source_sha||baseRelease.source_commit||"—"}</span></div><span className="mono">{baseRelease.sha256||baseRelease.checksum||"No checksum"}</span></div><div className="listrow"><div><b>Release notes</b><span>{baseRelease.notes||baseRelease.changelog||"No changelog supplied"}</span></div><Link className="buttonlink" href="/portal/orbitfs/releases">Full history</Link></div></div>}</section>
    <section className="panel"><div className="panelTitle"><div><p className="eyebrow">UPDATES</p><h2>Release updates</h2><p className="muted">Updates keep your existing Vercel project and database. Available components are shown in the release details.</p></div>{updateAvailable&&<span className="state ready">UPDATE AVAILABLE</span>}</div>{updateAvailable?<div className="listrow"><div><b>v{latestUpdate}</b><span>{updateRelease?.channel||"stable"} · {updateRelease?.status||"published"} · Published update available for your installation.</span></div><button disabled={!!busy} onClick={()=>void deploy("update",latestUpdate)}>{busy?"Updating…":"Install update"}</button></div>:<p className="muted">{install?.release_version?"You are on the latest published update.":"Deploy Base first."}</p>}<div style={{display:"flex",gap:8,marginTop:12,flexWrap:"wrap"}}><Link className="buttonlink" href="/portal/orbitfs/releases">View changelog</Link>{install?.release_version&&<button className="secondary" disabled={!!busy} onClick={()=>void deploy("rollback")}>{busy?"Working…":"Rollback"}</button>}</div></section>
    <section className="panel"><div className="listrow"><div><b>License</b><span>{binding?.remote_state||binding?.desired_state||"Unknown"}</span></div><Link className="buttonlink" href="/portal/orbitfs/license">Manage license</Link></div></section>{msg&&<section className="panel"><p>{msg}</p></section>}
  </>}</main>;
}
