"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

const hasBase=(b:any)=>b?.license_product_key==="orbitfs_base"||!!b?.components?.orbitfs_base||!!b?.components?.orbitfs_panel;
const pretty=(v:any)=>String(v||"waiting").replaceAll("_"," ");

export default function OrbitFSDeploymentCenter(){
  const sb=useMemo(()=>createClient(),[]);
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
  async function auth():Promise<HeadersInit>{const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token`}}:{}};
  async function load(){setLoading(true);setMsg("");try{const r=await fetch("/api/orbitfs/status",{headers:await auth(),cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Could not load deployment status (${r.status})`);setData(j)}catch(e:any){setMsg(e?.message||"Could not load deployment status.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const binding=(data?.bindings||[]).find(hasBase)||data?.bindings?.[0],install=(data?.installations||[]).find((x:any)=>x.license_binding_id===binding?.id),latestBase=data?.latestBase?.version,latestUpdate=data?.latestUpdate?.version,releases=(data?.releases||[]).filter((x:any)=>!install?.id||!x.installation_id||x.installation_id===install.id),updateAvailable=!!install?.release_version&&!!latestUpdate&&install.release_version!==latestUpdate;
  async function deploy(action:"deploy"|"update"|"rollback"|"redeploy",version?:string){if(!install)return setMsg("Open OrbitFS setup first and create your installation.");if(action==="rollback"&&!version){version=prompt("Release version to roll back to:",install.previous_release_version||"")||undefined;if(!version)return}if(!confirm(`${action} OrbitFS${version?` to ${version}`:""}?`))return;setBusy(`${action}:${version||""}`);try{const r=await fetch(`/api/orbitfs/installations/${install.id}/deploy`,{method:"POST",headers:{...(await auth()),"content-type":"application/json"},body:JSON.stringify({action,version})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`${action} failed.`);setMsg(j.message||`OrbitFS ${action} started.`);await load()}catch(e:any){setMsg(e?.message||`${action} failed.`)}finally{setBusy("")}}
  async function control(action:"rotate"|"unlock"){if(!binding?.license_id)return setMsg("No License Master licence ID is available.");if(!confirm(action==="rotate"?"Rotate your licence key?":"Unlock this installation?"))return;setBusy(action);try{const r=await fetch("/api/orbitfs/license-control",{method:"POST",headers:{...(await auth()),"content-type":"application/json"},body:JSON.stringify({licenseId:binding.license_id,installationId:install?.id||null,action})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Licence ${action} failed.`);setMsg(j.message||`Licence ${action} completed.`);await load()}catch(e:any){setMsg(e?.message||`Licence ${action} failed.`)}finally{setBusy("")}}
  if(loading)return <main className="portalOverviewV2"><section className="panel"><h2>Loading OrbitFS Deployment Center…</h2><p className="muted">Checking your customer deployment, releases and licence authority.</p></section></main>;
  return <main className="portalOverviewV2"><header className="portalOverviewHero"><div><p className="eyebrow">ORBITFS · DEPLOYMENT CENTER</p><h1>Deploy & manage OrbitFS</h1><p className="muted">The customer-side control center for your Base deployment, published releases and License Master controls.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="buttonlink" href="/portal/orbitfs">Setup & accounts</Link><Link className="buttonlink" href="/portal/orbitfs/releases">Release details</Link><Link className="buttonlink" href="/portal/orbitfs/license">License Controller</Link></div></header>
    {!data?<section className="panel"><h2>Deployment status unavailable</h2><p className="muted">{msg}</p><button onClick={()=>void load()}>Retry</button></section>:<>
      <div className="portalOverviewStats"><div className="portalStatCard"><span className="portalStatIcon">B</span><div><small>BASE</small><strong>{install?.release_version||"Not deployed"}</strong><span>{install?.state?pretty(install.state):"Setup required"}</span></div></div><div className="portalStatCard"><span className="portalStatIcon">D</span><div><small>DATABASE</small><strong>{install?.database_initialized_at?"Ready":"Not initialized"}</strong><span>{install?.supabase_project_name||"Customer Supabase"}</span></div></div><div className="portalStatCard"><span className="portalStatIcon">V</span><div><small>VERCEL</small><strong>{install?.vercel_project_id?"Connected":"Not deployed"}</strong><span>{install?.vercel_project_name||"Customer Vercel"}</span></div></div><div className="portalStatCard"><span className="portalStatIcon">L</span><div><small>LICENSE</small><strong>{binding?.remote_state||binding?.desired_state||"Unknown"}</strong><span>{binding?.license_key_last4?`••••${binding.license_key_last4}`:"Protected"}</span></div></div></div>
      {!install&&<section className="panel"><p className="eyebrow">BASE DEPLOYMENT</p><h2>Set up your OrbitFS installation</h2><p className="muted">Connect your Supabase and Vercel accounts, select or create the customer database, initialize the OrbitFS schema, then deploy the Base Panel.</p><Link className="buttonlink" href="/portal/orbitfs">Open setup</Link></section>}
      {install&&<><section className="panel"><div className="panelTitle"><div><p className="eyebrow">BASE SYSTEM</p><h2>{install.vercel_project_name||"OrbitFS Base"}</h2><p className="muted">Published Base release {latestBase||"not available"}. Deployment runs against the customer's connected Vercel and Supabase accounts.</p></div><span className={`state ${install.state==="ready"?"ready":"waiting"}`}>{pretty(install.state)}</span></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={!!busy||!latestBase} onClick={()=>void deploy(install.release_version?"redeploy":"deploy",latestBase)}>{busy.startsWith("deploy:")?"Deploying…":install.release_version?"Redeploy Base":"Deploy Base"}</button><Link className="buttonlink" href="/portal/orbitfs">Configure deployment</Link></div></section>
        <section className="panel"><div className="panelTitle"><div><p className="eyebrow">RELEASE DEPLOYER</p><h2>Published OrbitFS updates</h2><p className="muted">Only releases published through the License Master → Billing Store publication flow are available here.</p></div>{updateAvailable&&<span className="state ready">UPDATE AVAILABLE</span>}</div>{updateAvailable&&<div className="listrow"><div><b>v{latestUpdate}</b><span>Published update available for this installation.</span></div><button disabled={!!busy} onClick={()=>void deploy("update",latestUpdate)}>{busy.startsWith("update:")?"Deploying…":"Deploy update"}</button></div>}{releases.length?releases.slice(0,8).map((r:any)=><div className="listrow" key={r.id||r.version}><div><b>v{r.version||r.name}</b><span>{r.component||r.product_code||"ORBITFS"} · {r.channel||"stable"}{r.published_at?` · ${new Date(r.published_at).toLocaleString()}`:""}</span></div><button className="secondary" disabled={!!busy||install.release_version===r.version} onClick={()=>void deploy("update",r.version)}>{install.release_version===r.version?"Installed":busy===`update:${r.version}`?"Deploying…":"Deploy"}</button></div>):<p className="muted">No published releases are currently available.</p>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><Link className="buttonlink" href="/portal/orbitfs/releases">View full release history</Link>{install.release_version&&<button className="secondary" disabled={!!busy} onClick={()=>void deploy("rollback")}>{busy.startsWith("rollback:")?"Rolling back…":"Rollback"}</button>}</div></section>
        <section className="panel"><div className="panelTitle"><div><p className="eyebrow">LICENSE CONTROLLER</p><h2>License Master authority</h2><p className="muted">Licensing remains authoritative in License Master. The Store does not create, sign or replace the licence authority.</p></div><span className="state">{binding?.remote_state||binding?.desired_state||"unknown"}</span></div><div className="listrow"><div><b>License</b><span>{binding?.license_key_last4?`••••${binding.license_key_last4}`:"Protected"} · {install.installation_id||"Installation"}</span></div><div style={{display:"flex",gap:8}}><button disabled={!!busy||!binding?.license_id} onClick={()=>void control("rotate")}>{busy==="rotate"?"Rotating…":"Rotate key"}</button><button className="secondary" disabled={!!busy||!binding?.license_id} onClick={()=>void control("unlock")}>{busy==="unlock"?"Unlocking…":"Unlock installation"}</button></div></div><Link className="buttonlink" href="/portal/orbitfs/license" style={{marginTop:12}}>Open License Controller</Link></section>
      </>}
      {msg&&<section className="panel"><p>{msg}</p></section>}
    </>}
  </main>;
}
