"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";
type Row=Record<string,any>;
const productName=(x:any)=>({orbitfs_base:"OrbitFS Base",orbitfs_apex:"OrbitFS APEX",orbitfs_mcp:"OrbitFS MCP",orbitfs_studio:"OrbitFS Studio"}[String(x||"").toLowerCase()]||String(x||"OrbitFS licence"));
export default function LicenseControllerPage(){
 const sb=useMemo(()=>createClient(),[]);
 const [customers,setCustomers]=useState<Row[]>([]),[customerQuery,setCustomerQuery]=useState(""),[customerId,setCustomerId]=useState(""),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[masterQuery,setMasterQuery]=useState(""),[newKey,setNewKey]=useState("");
 async function getToken(){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw Error("Administrator session expired.");return session.access_token}
 async function loadCustomers(){const {data,error}=await sb.from("customers").select("id,auth_user_id,user_id,customer_number,name,email").not("auth_user_id","is",null).order("created_at",{ascending:false});if(error)throw error;setCustomers(data||[])}
 async function loadCustomer(id=customerId){if(!id){setData(null);return}setLoading(true);setError("");try{const t=await getToken();const r=await fetch("/api/admin/license-link?customerId="+encodeURIComponent(id),{headers:{Authorization:"Bearer "+t},cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Could not load customer licences.");setData(j)}catch(e:any){setError(e?.message||"Could not load customer licences.");setData(null)}finally{setLoading(false)}}
 useEffect(()=>{loadCustomers().catch(e=>setError(e?.message||"Could not load customers."))},[]);
 useEffect(()=>{if(customerId)void loadCustomer(customerId)},[customerId]);
 const filteredCustomers=customers.filter(c=>{const q=customerQuery.trim().toLowerCase();if(!q)return true;return [c.name,c.email,c.customer_number,c.id].some(v=>String(v||"").toLowerCase().includes(q))}).slice(0,30);
 const selectedCustomer=data?.customer||customers.find(c=>c.id===customerId);
 const linkedIds=new Set((data?.bindings||[]).map((b:any)=>String(b.license_id||"")));
 const available=(data?.allLicenses||[]).filter((x:any)=>!linkedIds.has(String(x.id||x.license_id||""))).filter((x:any)=>{const q=masterQuery.trim().toLowerCase();if(!q)return true;return [x.id,x.product_code,x.product,x.status,x.customer_external_id,x.external_reference,x.order_ref].some(v=>String(v||"").toLowerCase().includes(q))});
 async function link(licenseId="",mode="manual"){setBusy(mode+":"+licenseId);setError("");setMessage("");try{const t=await getToken();const r=await fetch("/api/admin/license-link",{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({customerId,licenseId,mode})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Could not link licence.");setMessage(productName(j.product)+" linked"+(mode==="auto"&&j.matchReason?" · matched by "+j.matchReason:"")+"." );await loadCustomer(customerId)}catch(e:any){setError(e?.message||"Could not link licence.")}finally{setBusy("")}}
 async function control(licenseId:string,action:string){if(!confirm(action==="rotate"?"Rotate this licence key? The replacement key will be shown once.":"Apply "+action+" to this licence?"))return;setBusy(action+":"+licenseId);setError("");setMessage("");try{const t=await getToken();const r=await fetch("/api/admin/license-master?path="+encodeURIComponent("/api/license/"+encodeURIComponent(licenseId)+"/control"),{method:"POST",headers:{Authorization:"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify({action,actorRef:"billing_store_license_controller"})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||("Licence "+action+" failed."));const key=j?.key||j?.license?.key||j?.license_key||j?.licenseKey||"";if(action==="rotate"){if(!key)throw Error("License Master completed rotation but did not return the replacement key.");setNewKey(String(key))}setMessage(j.message||("Licence "+action+" completed."));await loadCustomer(customerId)}catch(e:any){setError(e?.message||("Licence "+action+" failed."))}finally{setBusy("")}}
 return <main className="lmPage licenseControllerPage">
  <header className="lmHero"><div><div className="lmEyebrow">LICENSE MANAGEMENT · CUSTOMER LINKING</div><h1>Customer License Manager</h1><p>One place to find a customer, see their linked licences, and attach an existing License Master licence. Linking does not issue a new licence.</p></div><button onClick={()=>{void loadCustomers();if(customerId)void loadCustomer(customerId)}} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></header>
  <section className="lmCard assignmentPicker"><div><div className="lmKicker">CUSTOMER</div><h2>Select customer</h2><p className="lmHint">Search by name, email, customer number or customer record ID.</p></div><input value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)} placeholder="Search customer…"/><div className="customerPickerList">{filteredCustomers.map(c=><button type="button" className={customerId===c.id?"customerPick active":"customerPick"} key={c.id} onClick={()=>setCustomerId(c.id)}><span><b>{c.name||"Unnamed customer"}</b><small>{c.email||"No email"} · {c.customer_number||c.id}</small></span>{customerId===c.id&&<strong>Selected</strong>}</button>)}{!filteredCustomers.length&&<p className="muted">No customers found.</p>}</div></section>
  {error&&<section className="lmCard lmError" role="alert"><b>Action failed</b><p>{error}</p></section>}{message&&<section className="lmCard lmSuccess" role="status"><b>{message}</b></section>}
  {selectedCustomer&&<section className="lmCard customerSummary"><div><div className="lmKicker">CUSTOMER</div><h2>{selectedCustomer.name||"Customer"}</h2><p>{selectedCustomer.email||"No email"} · <b>{selectedCustomer.customer_number||"No customer number"}</b></p></div><div className="customerFacts"><span><small>Customer record</small><b>{selectedCustomer.id}</b></span><span><small>Account ID</small><b>{selectedCustomer.auth_user_id||selectedCustomer.user_id||"—"}</b></span></div><button disabled={!!busy} onClick={()=>void link("","auto")}>{busy==="auto:"?"Linking…":"Auto-link licence"}</button></section>}
  {selectedCustomer&&<section className="lmCard"><div className="sectionHeading"><div><div className="lmKicker">LINKED LICENSES</div><h2>Licences on this customer</h2><p className="lmHint">This is the customer’s single licence list. Controls below call License Master.</p></div><span className="countBadge">{(data?.bindings||[]).length}</span></div>{loading?<div className="emptyState">Loading…</div>:(data?.bindings||[]).length===0?<div className="emptyState"><b>No licence is linked to this customer.</b><span>Use Auto-link or choose an existing licence from the inventory below.</span></div>:<div className="linkedList">{(data?.bindings||[]).map((b:any)=><article className="licenseRow" key={b.id}><div className="licenseMain"><div><b>{productName(b.license_product_key||b.label)}</b><span>Master ID · {b.license_id}</span></div><span className={"stateDot "+String(b.remote_state||b.desired_state||"unknown").toLowerCase()}>{b.remote_state||b.desired_state||"unknown"}</span></div><div className="licenseMeta"><span>Key <b>{b.license_key_last4?"••••"+b.license_key_last4:"Protected"}</b></span><span>Expires <b>{b.expires_at?new Date(b.expires_at).toLocaleDateString():"Never"}</b></span></div><div className="licenseActions"><button disabled={!!busy} onClick={()=>void control(String(b.license_id),"unlock")}>{busy==="unlock:"+b.license_id?"Working…":"Unlock"}</button><button disabled={!!busy} onClick={()=>void control(String(b.license_id),"rotate")}>{busy==="rotate:"+b.license_id?"Rotating…":"Rotate key"}</button><button className="secondary" disabled={!!busy} onClick={()=>void control(String(b.license_id),"suspend")}>{busy==="suspend:"+b.license_id?"Working…":"Suspend"}</button></div></article>)}</div>}</section>}
  {selectedCustomer&&<section className="lmCard"><div className="sectionHeading"><div><div className="lmKicker">LICENSE MASTER INVENTORY</div><h2>Link an existing licence</h2><p className="lmHint">These are existing Master records. The Link button only creates the Billing Store customer binding.</p></div></div><input value={masterQuery} onChange={e=>setMasterQuery(e.target.value)} placeholder="Search licence ID, product, status, customer reference or order…"/><div className="masterInventory">{available.slice(0,50).map((x:any)=><div className="inventoryRow" key={String(x.id||x.license_id)}><div><b>{productName(x.product_code||x.product)}</b><span>{x.id||x.license_id} · {x.status||"unknown"}{x.customer_external_id?" · Customer ref "+x.customer_external_id:""}</span></div><button disabled={!!busy} onClick={()=>void link(String(x.id||x.license_id))}>{busy==="manual:"+String(x.id||x.license_id)?"Linking…":"Link to customer"}</button></div>)}{!available.length&&<div className="emptyState"><b>No unlinked licences match.</b><span>Manual linking never creates a new License Master licence.</span></div>}</div></section>}
  {newKey&&<section className="lmCard newKeyBox" role="status"><div className="lmKicker">NEW LICENSE KEY</div><h2>Replacement key</h2><p className="muted">Shown once. Save it before leaving this page.</p><code>{newKey}</code><div><button onClick={()=>void navigator.clipboard?.writeText(newKey)}>Copy key</button><button className="secondary" onClick={()=>setNewKey("")}>Dismiss</button></div></section>}
 </main>;
}