import {createClient} from "@supabase/supabase-js";
import {masterDeployments,masterInstallations,masterLicenses,masterProducts,masterReleases,masterRevision,masterSettings} from "@/lib/master-api";
export const dynamic="force-dynamic";
const supabaseUrl=()=>String(process.env.NEXT_PUBLIC_SUPABASE_URL||"");
const supabaseKey=()=>String(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"");
async function currentUser(req:Request){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token||!supabaseUrl()||!supabaseKey())throw Object.assign(new Error("Authentication is unavailable"),{status:401});const sb=createClient(supabaseUrl(),supabaseKey(),{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const {data,error}=await sb.auth.getUser(token);if(error||!data.user)throw Object.assign(new Error("Unauthorized"),{status:401});return data.user;}
const rows=(value:any,key:string)=>Array.isArray(value?.[key])?value[key]:[];
const ownsLicense=(l:any,userId:string)=>String(l?.customer_ref||l?.auth_user_id||"")===userId;
export async function GET(req:Request){try{const user=await currentUser(req);const [settings,products,revision,licensesResult,releasesResult,installationsResult,deploymentsResult]=await Promise.all([masterSettings(),masterProducts(),masterRevision(),masterLicenses(),masterReleases(),masterInstallations(),masterDeployments()]);const licenses=rows(licensesResult,"licenses").filter((l:any)=>ownsLicense(l,user.id));const licenseIds=new Set(licenses.map((l:any)=>String(l.id)));const orderRefs=new Set(licenses.map((l:any)=>String(l.order_ref||"")).filter(Boolean));const installations=rows(installationsResult,"installations").filter((i:any)=>licenseIds.has(String(i.license_id||i.licenseId||i.license_binding_id||""))||orderRefs.has(String(i.order_ref||"")));const installationIds=new Set(installations.map((i:any)=>String(i.id)));const deployments=rows(deploymentsResult,"deployments").filter((d:any)=>installationIds.has(String(d.installation_id||d.installationId||"")));const releases=rows(releasesResult,"releases");const published=releases.filter((r:any)=>String(r.status||"")==="published").sort((a:any,b:any)=>String(b.updatedAt||b.updated_at||b.publishedAt||"").localeCompare(String(a.updatedAt||a.updated_at||a.publishedAt||"")));return Response.json({authority:"orbitfs-license-master-v2",sections:{licensing:{licenses,products:rows(products,"products"),revision},releases:{releases,latest:published[0]||null},baseDeployment:{installations,deployments}},settings},{headers:{"cache-control":"no-store"}})}catch(e:any){return Response.json({error:e?.message||"License Master unavailable"},{status:Number(e?.status)||503,headers:{"cache-control":"no-store"}})}}
