import {masterProducts,masterRequest} from "@/lib/master-api";
import {licenseDb} from "@/lib/license-api";
import {requireOrbitDeploymentAdmin} from "@/lib/orbitfs-deployment-auth";
import {DEFAULT_MASTER_API_URL,normalizeMasterApiUrl} from "@/lib/license-master-config";
const MASTER_URL=DEFAULT_MASTER_API_URL;
const canonicalProducts=["orbitfs_base","orbitfs_mcp","orbitfs_apex","orbitfs_studio"];
const cleanError=(e:any)=>String(e?.message||"License Master connection test failed").slice(0,1000);
async function localMappings(){const {data,error}=await licenseDb().from("products").select("id,name,slug,license_product_key,license_api_url,license_api_mode,license_api_enabled,active").in("license_product_key",canonicalProducts).order("license_product_key");if(error)throw error;return data||[];}
export async function GET(req:Request){try{await requireOrbitDeploymentAdmin(req);const {data,error}=await licenseDb().from("license_master_connection").select("id,master_url,enabled,last_tested_at,last_success_at,last_error,updated_at").order("updated_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;const products=await masterProducts();const local=await localMappings();const rows=Array.isArray(products?.products)?products.products:[];const by=new Map(rows.map((p:any)=>[String(p.code||p.slug||"").toLowerCase(),p]));const connections=canonicalProducts.map(code=>({code,master:by.get(code)||null,local:local.find((p:any)=>String(p.license_product_key||"").toLowerCase()===code)||null,connected:Boolean(by.get(code)&&local.find((p:any)=>String(p.license_product_key||"").toLowerCase()===code&&p.license_api_mode==="master"&&p.license_api_enabled!==false))}));return Response.json({connection:data||null,configuredUrl:data?.master_url||MASTER_URL,masterPanelUrl:"https://panel.incendiarynetworks.cc",connections,masterProducts:rows},{headers:{"cache-control":"no-store"}});}catch(e:any){return Response.json({error:cleanError(e)},{status:Number(e?.status)||502,headers:{"cache-control":"no-store"}})}}
export async function POST(req:Request){try{await requireOrbitDeploymentAdmin(req);const db=licenseDb();const body=await req.json().catch(()=>({}));if(body.action==="save"){const requested=String(body.masterUrl||"").trim();const masterUrl=normalizeMasterApiUrl(requested);if(requested&&masterUrl!==requested.replace(/\/$/,""))return Response.json({error:"Invalid License Master API URL. Use the approved HTTPS License Master API endpoint."},{status:400});const now=new Date().toISOString();const {data:row}=await db.from("license_master_connection").select("id").order("updated_at",{ascending:false}).limit(1).maybeSingle();if(row)await db.from("license_master_connection").update({master_url:masterUrl,enabled:true,updated_at:now,last_error:null}).eq("id",row.id);else await db.from("license_master_connection").insert({master_url:masterUrl,enabled:true,last_error:null});return Response.json({ok:true,configuredUrl:masterUrl},{headers:{"cache-control":"no-store"}});}const started=Date.now();const [health,products]=await Promise.all([masterRequest("/api/v1/license/health",{method:"GET"},"billing"),masterProducts()]);const rows=Array.isArray(products?.products)?products.products:[];if(!rows.some((p:any)=>canonicalProducts.includes(String(p.code||p.slug||"").toLowerCase())))throw new Error("License Master returned no canonical OrbitFS products.");const now=new Date().toISOString();const {data:row}=await db.from("license_master_connection").select("id").order("updated_at",{ascending:false}).limit(1).maybeSingle();if(row)await db.from("license_master_connection").update({master_url:MASTER_URL,enabled:true,last_tested_at:now,last_success_at:now,last_error:null,updated_at:now}).eq("id",row.id);else await db.from("license_master_connection").insert({master_url:MASTER_URL,enabled:true,last_tested_at:now,last_success_at:now,last_error:null});return Response.json({ok:true,latencyMs:Date.now()-started,health,productCount:rows.length,products:rows},{headers:{"cache-control":"no-store"}});}catch(e:any){const message=cleanError(e);return Response.json({ok:false,error:message},{status:Number(e?.status)||502,headers:{"cache-control":"no-store"}})}}
