import {masterHealth,masterProducts} from "@/lib/master-api";
import {licenseDb} from "@/lib/license-api";
import {requireOrbitDeploymentAdmin} from "@/lib/orbitfs-deployment-auth";

const DEFAULT_MASTER_URL="https://incendiarynetworks.cc/api";
const PANEL_URL="https://panel.incendiarynetworks.cc";
const LEGACY_URL="https://api.incendiarynetworks.cc";
const canonicalProducts=["orbitfs_base","orbitfs_mcp","orbitfs_apex","orbitfs_studio"];
function cleanError(e:any){return String(e?.message||"License Master connection test failed").slice(0,1000);}
function validMasterUrl(value:string){const u=new URL(String(value||"").trim());if(u.protocol!=="https:"||u.hostname!=="incendiarynetworks.cc"||u.pathname.replace(/\/$/,"")!=="/api"||u.search||u.hash)throw new Error("Master API must be https://incendiarynetworks.cc/api");return DEFAULT_MASTER_URL;}
async function row(){const {data,error}=await licenseDb().from("license_master_connection").select("id,master_url,enabled,last_tested_at,last_success_at,last_error,updated_at").order("updated_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data||null;}
async function localMappings(){const {data,error}=await licenseDb().from("products").select("id,name,slug,license_product_key,license_api_url,license_api_mode,license_api_enabled,active").in("license_product_key",canonicalProducts).order("license_product_key");if(error)throw error;return data||[];}
export async function GET(req:Request){try{await requireOrbitDeploymentAdmin(req);const data=await row();const products=await masterProducts();const local=await localMappings();const masterRows=Array.isArray(products?.products)?products.products:[];const masterBySlug=new Map(masterRows.map((p:any)=>[String(p.code||p.slug||"").toLowerCase(),p]));const connections=canonicalProducts.map(code=>({code,master:masterBySlug.get(code)||null,local:local.find((p:any)=>String(p.license_product_key||"").toLowerCase()===code)||null,connected:Boolean(masterBySlug.get(code)&&local.find((p:any)=>String(p.license_product_key||"").toLowerCase()===code&&p.license_api_mode==="master"&&p.license_api_enabled!==false))}));return Response.json({connection:data,configuredUrl:data?.master_url||DEFAULT_MASTER_URL,masterPanelUrl:PANEL_URL,legacyUrlBlocked:true,connections,masterProducts:masterRows},{headers:{"cache-control":"no-store"}});}catch(e:any){return Response.json({error:cleanError(e)},{status:Number(e?.status)||502,headers:{"cache-control":"no-store"}})}}
export async function POST(req:Request){try{await requireOrbitDeploymentAdmin(req);const body=await req.json().catch(()=>({}));const requested=String(body?.masterUrl||body?.master_url||"").trim();const url=validMasterUrl(requested||DEFAULT_MASTER_URL);const db=licenseDb();const now=new Date().toISOString();const current=await row();if(current)await db.from("license_master_connection").update({master_url:url,enabled:true,last_tested_at:now,last_success_at:now,last_error:null,updated_at:now}).eq("id",current.id);else await db.from("license_master_connection").insert({master_url:url,enabled:true,last_tested_at:now,last_success_at:now,last_error:null});const started=Date.now();const [health,products]=await Promise.all([masterHealth(),masterProducts()]);return Response.json({ok:true,latencyMs:Date.now()-started,health,productCount:Array.isArray(products?.products)?products.products.length:0,products:products?.products||[],savedUrl:url},{headers:{"cache-control":"no-store"}});}catch(e:any){return Response.json({ok:false,error:cleanError(e)},{status:Number(e?.status)||502,headers:{"cache-control":"no-store"}})}}
export async function PATCH(req:Request){return POST(req);}
