"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

export default function MyOrbitFSAdmin(){
 const sb=useMemo(()=>createClient(),[]),[data,setData]=useState<any>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 async function headers(){const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}}
 async function load(){setBusy("load");try{const r=await fetch("/api/admin/orbitfs",{headers:await headers(),cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Could not load OrbitFS releases");setData(j);setMsg("")}catch(e:any){setMsg(e?.message||"Could not load OrbitFS releases")}finally{setBusy("")}}
 useEffect(()=>{void load()},[]);
 const base=data?.latestBase,update=data?.latestUpdate,releases=(data?.releases||[]).filter((r:any)=>r.status==="published").sort((a:any,b:any)=>String(b.publishedAt||b.updatedAt).localeCompare(String(a.publishedAt||a.updatedAt)));
 async function rollback(i:any){const version=prompt("Rollback installation to version:",i.previous_release_version||"");if(!version)return;if(!confirm(`Rollback ${i.vercel_project_name||"this installation"} to ${version}?`))return;setBusy(i.id);try{const r=await fetch("/api/admin/orbitfs/deploy",{method:"POST",headers:{...(await headers()),"content-type":"application/json"},body:JSON.stringify({installationId:i.id,action:"rollback",version})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Rollback failed");setMsg(`Rollback to ${version} started.`);await load()}catch(e:any){setMsg(e?.message||"Rollback failed")}finally{setBusy("")}}
 return <main className="lmPage"><div className="lmHero"><div><div className="lmEyebrow">ORBITFS ADMIN</div><h1>Release control</h1><p>Simple Base version control here. Detailed component updates live in the Update Release system.</p></div><button onClick={()=>void load()} disabled={busy==="load"}>{busy==="load"?"Refreshing…":"Refresh"}</button></div>
 <div className="lmGrid2"><section className="lmCard"><div className="lmKicker">CURRENT BASE</div><h2>{base?.version||"No Base release"}</h2><p className="muted">{base?.title||"The latest published Base release from License Master."}</p></section><section className="lmCard"><div className="lmKicker">LATEST UPDATE</div><h2>{update?.version||"No update"}</h2><p className="muted">{update?.title||"Published update release."}</p></section></div>
 <section className="lmCard" style={{marginTop:14}}><div className="lmKicker">CHANGELOG</div><h2>Published releases</h2>{releases.length?releases.map((r:any)=><div className="listrow" key={r.releaseId||r.id}><div><b>{r.version}</b><span>{r.channel||r.release_type} · {r.status}</span><small style={{whiteSpace:"pre-wrap"}}>{r.changelog||r.notes||"No changelog"}</small></div><span>{r.release_type||r.channel}</span></div>):<p className="muted">No published releases.</p>}</section>
 <section className="lmCard" style={{marginTop:14}}><div className="lmKicker">INSTALLATIONS</div><h2>Version control</h2>{(data?.installations||[]).filter((i:any)=>i.release_version).map((i:any)=><div className="listrow" key={i.id}><div><b>{i.customer?.display_name||i.customer?.company_name||i.customer?.email||"Customer"}</b><span>{i.vercel_project_name||"Vercel"} · installed {i.release_version}</span></div><button disabled={!!busy} onClick={()=>void rollback(i)}>{busy===i.id?"Rolling back…":"Rollback"}</button></div>)}{!(data?.installations||[]).filter((i:any)=>i.release_version).length&&<p className="muted">No deployed installations.</p>}</section>
 <div style={{display:"flex",gap:8,marginTop:14,flexWrap:"wrap"}}><Link className="buttonlink" href="/admin/orbitfs/base-deploy">Base deployment</Link><Link className="buttonlink" href="/admin/orbitfs/update-release-deployer">Update releases</Link><Link className="buttonlink" href="/admin/license-controller">License Master</Link></div>{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}
 </main>;
}
