"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase";

const editable=["title","description","changelog","customer_notes","internal_notes","severity","rollout","minimum_version","rollback_version"] as const;
export default function MyOrbitFSAdmin(){const sb=useMemo(()=>createClient(),[]),[data,setData]=useState<any>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
async function headers(){const h=new Headers();const {data:{session}}=await sb.auth.getSession();if(session?.access_token)h.set("Authorization",`Bearer ${session.access_token}`);return h}
async function load(){setBusy("load");try{const r=await fetch("/api/admin/orbitfs",{headers:await headers(),cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Could not load OrbitFS releases");setData(j);setMsg("")}catch(e:any){setMsg(e?.message||"Could not load OrbitFS releases")}finally{setBusy("")}}
useEffect(()=>{void load()},[]);
const releases=(data?.releases||[]).filter((r:any)=>r.releaseType==="update"||r.release_type==="update");
async function save(r:any,form:HTMLFormElement){setBusy(r.releaseId||r.id);try{const body:any={releaseId:r.releaseId||r.id};for(const key of editable){const el=form.elements.namedItem(key) as HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement|null;if(el)body[key]=el.type==="checkbox"?(el as HTMLInputElement).checked:el.value}const h=await headers();h.set("content-type","application/json");const res=await fetch("/api/admin/orbitfs",{method:"PATCH",headers:h,body:JSON.stringify(body)}),j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j.error||"Could not save release");setMsg("Release editor changes saved.");await load()}catch(e:any){setMsg(e?.message||"Could not save release")}finally{setBusy("")}}
async function publish(r:any){if(!confirm(`Publish Engine Update ${r.version} to the customer portal?`))return;setBusy(r.releaseId||r.id);try{const h=await headers();h.set("content-type","application/json");const res=await fetch("/api/admin/orbitfs",{method:"POST",headers:h,body:JSON.stringify({action:"publish",releaseId:r.releaseId||r.id})}),j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j.error||"Could not publish release");setMsg("Release published to the customer portal.");await load()}catch(e:any){setMsg(e?.message||"Could not publish release")}finally{setBusy("")}}
async function controlRelease(r:any,action:"archive"|"delete"){if(action==="delete"&&!confirm(`Permanently delete ${r.version}? This cannot be undone.`))return;if(action==="archive"&&!confirm(`Archive ${r.version}?`))return;setBusy(r.releaseId||r.id);try{const h=await headers();h.set("content-type","application/json");const res=await fetch("/api/admin/orbitfs",{method:"POST",headers:h,body:JSON.stringify({action,releaseId:r.releaseId||r.id})}),j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j.error||`Could not ${action} release`);setMsg(action==="archive"?"Release archived.":"Release permanently deleted.");await load()}catch(e:any){setMsg(e?.message||`Could not ${action} release`)}finally{setBusy("")}}
return <main className="lmPage"><div className="lmHero"><div><div className="lmEyebrow">ORBITFS ADMIN · FINAL REVIEW</div><h1>Release control</h1><p>Billing Store is the final customer-facing review and publication gate. License Master remains the technical authority.</p></div><button onClick={()=>void load()} disabled={busy==="load"}>{busy==="load"?"Refreshing…":"Refresh"}</button></div>
<section className="lmCard"><div className="lmKicker">UPDATE RELEASE REVIEW</div><h2>Engine Updates</h2><p className="muted">Only technically approved candidates can be edited or published here. Technical source, artifact, checksum and validation remain controlled by License Master.</p>
{releases.length?releases.map((r:any)=><ReleaseEditor key={r.releaseId||r.id} r={r} busy={busy} onSave={save} onPublish={publish} onArchive={controlRelease}/>):<p className="muted">No Engine Update candidates have reached Billing Store yet.</p>}</section>
<div style={{display:"flex",gap:8,marginTop:14,flexWrap:"wrap"}}><Link className="buttonlink" href="/admin/orbitfs/base-deployment">Base release</Link><Link className="buttonlink" href="/admin/orbitfs/update-release-deployer">Customer updates</Link><Link className="buttonlink" href="/admin/licensing">License Master</Link></div>{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</main>}

function ReleaseEditor({r,busy,onSave,onPublish,onArchive}:any){const editableOk=r.status!=="published"&&!r.archivedAt&&r.review_status==="approved";const canPublish=editableOk&&r.validation?.status==="passed"&&!!r.artifactUrl;return <details className="lmCard" style={{marginTop:14}} open={r.status==="draft"&&r.review_status==="approved"}><summary style={{cursor:"pointer"}}><b>{r.version}</b> · {r.channel} · {r.status} · review {r.review_status} · validation {r.validation?.status||"not run"}</summary><form onSubmit={e=>{e.preventDefault();void onSave(r,e.currentTarget)}} style={{display:"grid",gap:10,marginTop:14}}>
<div className="lmGrid2"><label>Title<input name="title" defaultValue={r.title||""}/></label><label>Severity<select name="severity" defaultValue={r.severity||"normal"}><option>normal</option><option>low</option><option>high</option><option>critical</option></select></label></div>
<label>Description<textarea name="description" rows={3} defaultValue={r.description||""}/></label>
<label>Changelog<textarea name="changelog" rows={12} defaultValue={r.changelog||""}/></label>
<div className="lmGrid2"><label>Customer notes<textarea name="customer_notes" rows={4} defaultValue={r.customerNotes||""}/></label><label>Internal notes<textarea name="internal_notes" rows={4} defaultValue={r.internalNotes||""}/></label></div>
<div className="lmGrid2"><label>Rollout<input name="rollout" defaultValue={r.rollout||"public"}/></label><label>Minimum Base/Engine version<input name="minimum_version" defaultValue={r.minimumVersion||""}/></label></div>
<div className="lmGrid2"><label>Rollback version<input name="rollback_version" defaultValue={r.rollbackVersion||""}/></label><label>Artifact<input value={r.artifactName||"Missing"} readOnly/></label></div>
<div className="notice"><b>Visibility checks</b><br/>Technical approval: {r.review_status==="approved"?"PASS":"BLOCKED"} · Validation: {r.validation?.status==="passed"?"PASS":"BLOCKED"} · Artifact: {r.artifactUrl?"PASS":"BLOCKED"} · Archived: {r.archivedAt?"BLOCKED":"PASS"}<br/>Publication is enabled only when all required checks pass.</div>
<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="submit" disabled={!editableOk||!!busy}>{busy?"Saving…":"Save editor changes"}</button>{canPublish&&<button type="button" disabled={!!busy} onClick={()=>void onPublish(r)}>Final review · Publish</button>}{!r.archivedAt?<button type="button" disabled={!!busy} onClick={()=>void onArchive(r,"archive")}>Archive</button>:null}</div>
</form></details>}
