"use client";
import {useEffect,useMemo,useState} from "react";import Link from "next/link";import {createClient} from "@/lib/supabase";
export default function OrbitFSReleaseDeployer(){const sb=useMemo(()=>createClient(),[]),[d,setD]=useState<any>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setMsg("");try{const {data:{session}}=await sb.auth.getSession();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch("/api/orbitfs/status",{headers:session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{},cache:"no-store",signal:controller.signal});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Could not load releases (${r.status})`);setD(j)}finally{clearTimeout(timer)}}catch(e:any){setD(null);setMsg(e?.name==="AbortError"?"License Master status request timed out. Please retry.":e?.message||"Could not load releases.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const binding=(d?.bindings||[]).find((x:any)=>x.license_product_key==="orbitfs_base"||x.components?.orbitfs_base)||d?.bindings?.[0],install=(d?.installations||[]).find((x:any)=>x.license_binding_id===binding?.id),allowedChannels=Array.isArray(d?.settings?.release_channels)?d.settings.release_channels:["stable"];
 const releases=(d?.publishedReleases||[]).filter((x:any)=>(x.release_type==="base"||x.release_type==="update")&&allowedChannels.includes(String(x.channel||"stable")));
 const latest=releases.find((x:any)=>x.release_type==="update")||d?.latestUpdate;
 async function deploy(release:any){if(!install)return setMsg("Start your OrbitFS installation first.");const version=String(release?.version||"");if(!version)return setMsg("Release version is missing.");const releaseId=String(release?.releaseId||release?.id||"");const isUpdate=String(release?.release_type||release?.releaseType||"")==="update";const requested=releaseId&&!isUpdate?`release:${releaseId}`:isUpdate?`update:${version}`:version;if(!confirm(`Deploy OrbitFS ${isUpdate?"update ":""}${version}?`))return;setBusy(version);const {data:{session}}=await sb.auth.getSession();const r=await fetch(`/api/orbitfs/installations/${install.id}/deploy`,{method:"POST",headers:{...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}) ,"Content-Type":"application/json"},body:JSON.stringify({action:install.release_version?(isUpdate?"update":"deploy"):"deploy",version:requested})});const j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?(j.message||"Deployment started."):(j.error||"Deployment failed."));if(r.ok)await load()}
 if(loading)return <main className="portalOverviewV2"><section className="panel"><h2>Loading Release Deployer…</h2><p className="muted">Checking your OrbitFS installation and published releases.</p></section></main>;if(!d)return <main className="portalOverviewV2"><section className="panel"><h2>Release Deployer unavailable</h2><p className="muted">{msg||"Could not load the License Master release status."}</p><button onClick={()=>void load()}>Retry</button></section></main>;
 return <main className="portalOverviewV2"><header className="portalOverviewHero"><div><p className="eyebrow">RELEASE DEPLOYER</p><h1>OrbitFS releases</h1><p className="muted">Published releases, customer-visible changelogs and deployment updates.</p></div><div style={{display:"flex",gap:8}}><Link className="buttonlink" href="/portal/orbitfs">My OrbitFS</Link><Link className="buttonlink" href="/portal/orbitfs/license">License Controller</Link></div></header><section className="panel"><p className="eyebrow">CURRENT INSTALLATION</p><h2>{install?.vercel_project_name||"OrbitFS Panel"}</h2><p className="muted">Installed {install?.release_version?`v${install.release_version}`:"release not yet deployed"} · {install?.state||"waiting"}</p>{latest&&install?.release_version!==latest.version&&<div className="listrow"><div><b>Update available: v{latest.version}</b><span>{latest.title||"Published update"}</span></div><button disabled={!!busy} onClick={()=>void deploy(latest)}>{busy===latest.version?"Starting…":"Deploy update"}</button></div>}</section><div className="portalOverviewGrid">{releases.length?releases.map((r:any)=><article className="panel" key={r.id||r.version}><p className="eyebrow">{r.release_type==="base"?"ORBITFS BASE":"ORBITFS UPDATE"} · {r.channel||"stable"}</p><h2>{r.title||`v${r.version}`}</h2><p className="muted">v{r.version} · {r.published_at?new Date(r.published_at).toLocaleString():"Published release"}</p>{r.description&&<p>{r.description}</p>}<p className="eyebrow" style={{marginTop:14}}>CHANGELOG</p><div style={{whiteSpace:"pre-wrap"}}>{r.changelog||"No changelog supplied."}</div>{r.customer_notes&&<><p className="eyebrow" style={{marginTop:14}}>NOTES</p><div style={{whiteSpace:"pre-wrap"}}>{r.customer_notes}</div></>}<div style={{marginTop:14}}><button disabled={!!busy||!install} onClick={()=>void deploy(r)}>{busy===r.version?"Deploying…":install?.release_version===r.version?"Installed":r.release_type==="base"?"Deploy Base":"Deploy update"}</button></div></article>):<section className="panel"><h2>No customer-visible releases</h2><p className="muted">Published customer releases from License Master will appear here.</p></section>}</div>{msg&&<section className="panel"><p>{msg}</p></section>}</main>}
