"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

const state=(v:any)=>String(v||"").toLowerCase();
export default function OrbitFSReleases(){
 const [data,setData]=useState<any>({releases:[]}),[busy,setBusy]=useState(""),[msg,setMsg]=useState(""),[filter,setFilter]=useState("all");
 async function load(){setBusy("load");const r=await fetch("/api/admin/orbitfs/release-handoff?action=drafts",{cache:"no-store"}),j=await r.json().catch(()=>({}));setBusy("");if(!r.ok)return setMsg(j.error||"Could not load Master release drafts.");setData(j);setMsg("")}
 useEffect(()=>{void load()},[]);
 async function publish(id:string){if(!confirm("Publish this final release draft to customers?"))return;setBusy(id);const r=await fetch(`/api/admin/orbitfs/release-handoff?action=publish&id=${encodeURIComponent(id)}`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?"Release published to customers.":j.error||"Publication failed.");if(r.ok)await load()}
 async function retry(id:string){setBusy(id);const r=await fetch(`/api/admin/orbitfs/release-handoff?action=retry&id=${encodeURIComponent(id)}`,{method:"POST",body:"{}"}),j=await r.json().catch(()=>({}));setBusy("");setMsg(r.ok?"Store handoff retried.":j.error||"Retry failed.");if(r.ok)await load()}
 const releases=(data.releases||[]).filter((r:any)=>filter==="all"||r.channel===filter);
 return <main className="lmPage"><div className="lmHero"><div><div className="lmEyebrow">ORBITFS · RELEASE SYSTEM</div><h1>Release Publication</h1><p>License Master does the technical release work. This Store screen is the customer-publication gate for Base and Update releases.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="buttonlink" href="/admin/orbitfs">← My OrbitFS</Link><Link className="buttonlink" href="/admin/orbitfs/base-deploy">Base Deploy</Link><Link className="buttonlink" href="/admin/orbitfs/update-release-deployer">Update Deploy</Link><button onClick={()=>void load()} disabled={busy==="load"}>{busy==="load"?"Refreshing…":"Refresh"}</button></div></div>
 <section className="lmGrid2"><div className="lmCard"><div className="lmKicker">AUTHORITY</div><h2>License Master</h2><p className="muted">Source capture, SemVer validation, packaging, artifact integrity, release finalization and deployment authority stay in License Master.</p></div><div className="lmCard"><div className="lmKicker">THIS STORE</div><h2>Customer publication</h2><p className="muted">The Store receives the final draft and decides when it becomes visible to customers. Publishing here does not rebuild or alter the Master release.</p></div></section>
 <section className="lmCard" style={{marginTop:14}}><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{["all","base","update"].map(x=><button key={x} className={filter===x?"primary":"secondary"} onClick={()=>setFilter(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>{releases.length?<div className="lmReleaseList">{releases.map((r:any)=><article className="lmRelease" key={r.id}><div style={{minWidth:0,flex:1}}><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><b>{r.version}</b><span className="state waiting">{r.channel}</span><span className="state ready">{r.status}</span></div><small>{r.id} · source {r.sourceCommit||"—"}</small><p>{r.title||r.description||"No release description."}</p>{r.changelog&&<p style={{whiteSpace:"pre-wrap"}}>{r.changelog}</p>}<small>Handoff: {r.deliveryStatus||"pending"} · attempts {r.deliveryAttempts||0}{r.deliveryError?` · ${r.deliveryError}`:""}</small></div><div className="actions">{state(r.status)==="ready_for_store"&&<button className="primary" disabled={!!busy} onClick={()=>void publish(r.id)}>{busy===r.id?"Publishing…":"Publish to customers"}</button>}{r.deliveryStatus==="failed"&&<button disabled={!!busy} onClick={()=>void retry(r.id)}>Retry handoff</button>}</div></article>)}</div>:<div className="lmEmpty">No final release drafts are waiting for customer publication.</div>}{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</section>
 <section className="lmCard" style={{marginTop:14}}><div className="lmKicker">BOUNDARY</div><h2>Publication is separate from deployment</h2><p className="muted">Publishing makes a release customer-visible. Base deployment and Update deployment remain explicit deployment actions backed by License Master. Customers do not receive Master or Store service credentials.</p></section></main>;
}
