"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

export default function OrbitFSReleases(){
 const [data,setData]=useState<any>({releases:[]}),[busy,setBusy]=useState(""),[msg,setMsg]=useState(""),[filter,setFilter]=useState("all");
 async function load(){setBusy("load");const r=await fetch("/api/admin/orbitfs/release-handoff?action=published",{cache:"no-store"}),j=await r.json().catch(()=>({}));setBusy("");if(!r.ok)return setMsg(j.error||"Could not load published License Master releases.");setData(j);setMsg("")}
 useEffect(()=>{void load()},[]);
 const releases=(data.releases||[]).filter((r:any)=>filter==="all"||r.releaseType===filter);
 return <main className="lmPage"><div className="lmHero"><div><div className="lmEyebrow">ORBITFS · RELEASE SYSTEM</div><h1>Published Releases</h1><p>License Master is the release authority. Once a release is reviewed and published there, this Store receives the authoritative release metadata for customer delivery.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="buttonlink" href="/admin/orbitfs">← My OrbitFS</Link><Link className="buttonlink" href="/admin/orbitfs/base-deploy">Base Deploy</Link><Link className="buttonlink" href="/admin/orbitfs/update-release-deployer">Update Deploy</Link><button onClick={()=>void load()} disabled={busy==="load"}>{busy==="load"?"Refreshing…":"Refresh"}</button></div></div>
 <section className="lmGrid2"><div className="lmCard"><div className="lmKicker">UPSTREAM</div><h2>License Master</h2><p className="muted">V1-vercel-base submits the package and Release Drafter changelog. License Master captures the release, performs review and controls publication.</p></div><div className="lmCard"><div className="lmKicker">THIS STORE</div><h2>Customer delivery</h2><p className="muted">Only published releases are shown here. The Store does not approve or rewrite the Master release record.</p></div></section>
 <section className="lmCard" style={{marginTop:14}}><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{["all","base","update"].map(x=><button key={x} className={filter===x?"primary":"secondary"} onClick={()=>setFilter(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>{releases.length?<div className="lmReleaseList">{releases.map((r:any)=><article className="lmRelease" key={r.id}><div style={{minWidth:0,flex:1}}><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><b>{r.version}</b><span className="state waiting">{r.releaseType||"release"}</span><span className="state ready">published</span></div><small>{r.id} · source {r.sourceRepo||"—"} · {r.sourceRef||"—"}</small><p>{r.description||r.title||"Published OrbitFS release."}</p>{r.changelog&&<details><summary>Changelog</summary><pre style={{whiteSpace:"pre-wrap",marginTop:8}}>{r.changelog}</pre></details>}<div style={{display:"grid",gap:4,marginTop:10}}><small>Commit: {r.sourceCommit||"—"}</small><small>Package: {r.artifactName||"—"}</small><small>SHA-256: {r.checksum||"—"}</small><small>Artifact: {r.artifactUrl?<a href={r.artifactUrl} target="_blank" rel="noreferrer">Open package</a>:"—"}</small><small>Published: {r.publishedAt?new Date(r.publishedAt).toLocaleString():"—"}</small></div></div></article>)}</div>:<div className="lmEmpty">No published releases are currently available from License Master.</div>}{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</section>
 <section className="lmCard" style={{marginTop:14}}><div className="lmKicker">BOUNDARY</div><h2>Review happens in License Master</h2><p className="muted">The release pipeline is V1-vercel-base → License Master intake → License Master review → License Master publication → Billing Store. Deployment remains a separate operation.</p></section></main>;
}
