import {licenseDb} from "@/lib/license-api";
import {masterRequest} from "@/lib/master-api";
import {httpError,requireOrbitAdmin} from "@/lib/orbitfs-deployment";

async function bounded<T>(promise:PromiseLike<T>,fallback:T,ms=2500):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([Promise.resolve(promise),new Promise<T>(resolve=>{timer=setTimeout(()=>resolve(fallback),ms)})])}finally{if(timer)clearTimeout(timer)}}
function normalizeLocal(r:any){return r?{...r,releaseId:r.releaseId||r.release_id||r.id,sourceCommit:r.sourceCommit||r.base_source_commit||r.engine_source_commit||null,schemaVersion:r.schemaVersion||r.schema_version||null,releaseChannel:r.releaseChannel||r.release_channel||"stable",minimumVersion:r.minimumVersion||r.minimum_version||null,publishedAt:r.publishedAt||r.published_at||null,updatedAt:r.updatedAt||r.updated_at||null,required:r.required===true,components:Array.isArray(r.components)?r.components:[]}:null}
function normalizeMaster(r:any){const m=r?.manifest&&typeof r.manifest==="object"?r.manifest:{};return{id:r.id,releaseId:r.id,version:String(r.version||""),channel:r.channel||"stable",status:r.status||"draft",release_type:r.release_type||r.releaseType||"update",releaseType:r.release_type||r.releaseType||"update",title:m.title||`OrbitFS ${(r.release_type||r.releaseType)==="base"?"Base":"Update"} ${r.version}`,description:m.description||null,changelog:r.changelog||r.notes||null,customerNotes:m.customer_notes||m.customerNotes||"",internalNotes:m.internal_notes||m.internalNotes||"",severity:m.severity||"normal",required:m.required===true,rollout:m.rollout||"public",minimumVersion:m.minimum_version||m.minimumVersion||null,rollbackVersion:m.rollback_version||m.rollbackVersion||null,components:Array.isArray(m.components)?m.components:[],sourceCommit:r.source_sha||null,sourceRepo:r.source_repo||null,sourceRef:r.source_ref||null,checksum:r.checksum||null,artifactUrl:r.artifact_url||null,artifactName:r.artifact_name||null,artifactRunId:r.artifact_run_id||null,publishedAt:r.published_at||null,updatedAt:r.updated_at||r.created_at||null,validation:m.validation||null}}
export async function POST(req:Request){try{await requireOrbitAdmin(req);const body=await req.json().catch(()=>({}));const action=String(body?.action||"").toLowerCase();const releaseId=String(body?.releaseId||body?.release_id||"").trim();if(!releaseId)return Response.json({error:"releaseId is required"},{status:400});if(action==="archive")return Response.json(await masterRequest(`/api/v1/releases/${encodeURIComponent(releaseId)}`,{method:"POST",body:JSON.stringify({action:"archive"})},"billing"));if(action==="delete")return Response.json(await masterRequest(`/api/v1/releases/${encodeURIComponent(releaseId)}`,{method:"POST",body:JSON.stringify({action:"delete"})},"billing"));return Response.json({error:"Unsupported release action"},{status:400})}catch(e){return httpError(e)}}

export async function GET(req:Request){try{await requireOrbitAdmin(req);const db=licenseDb();const [inst,profiles,settingsRow,bundles,master]=await Promise.all([bounded(db.from("orbitfs_installations").select("*").order("created_at",{ascending:false}),{data:[],error:null} as any),bounded(db.from("user_profiles").select("id,display_name,company_name,email,status"),{data:[],error:null} as any),bounded(db.from("orbitfs_release_system_settings").select("*").eq("id","primary").maybeSingle(),{data:null,error:null} as any),bounded(db.from("orbitfs_release_bundles").select("*").order("updated_at",{ascending:false}).limit(100),{data:[],error:null} as any),bounded(masterRequest("/api/releases",{method:"GET"},"billing"),{releases:[]},4000)]);const installations=inst.data||[],profileMap=new Map((profiles.data||[]).map((p:any)=>[p.id,p]));const local=(bundles.data||[]).map(normalizeLocal).filter((r:any)=>r?.status==="published");const remote=Array.isArray((master as any)?.releases)?(master as any).releases.map(normalizeMaster).filter((r:any)=>r?.status==="published"):[];const byId=new Map<string,any>();for(const r of local)byId.set(String(r.releaseId||r.id),r);for(const r of remote)byId.set(String(r.releaseId||r.id),r);const releases=[...byId.values()].sort((a:any,b:any)=>String(b.publishedAt||b.updatedAt).localeCompare(String(a.publishedAt||a.updatedAt)));const latest=(channel:string)=>releases.find((r:any)=>r.channel===channel)||null;const s=settingsRow.data||{};return Response.json({installations:installations.map((i:any)=>({...i,customer:profileMap.get(i.auth_user_id)||null})),releases,latestBase:latest("base"),latestUpdate:latest("update"),settings:{enabled:s.enabled!==false,customer_deploy_enabled:s.customer_deploy_enabled!==false,customer_updates_enabled:s.customer_updates_enabled!==false,customer_rollbacks_enabled:s.customer_rollbacks_enabled!==false}},{headers:{"cache-control":"no-store"}})}catch(e){return httpError(e)}}
