"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

export default function ReleaseChannelsAdmin(){
 const sb=useMemo(()=>createClient(),[]);
 const [data,setData]=useState<any>({channels:[],access:[],customers:[]}),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 const authHeaders=async()=>{const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw Error("Administrator session expired. Sign in again.");return {Authorization:`Bearer ${session.access_token}`};};
 const load=async()=>{setBusy("load");setMsg("");try{const r=await fetch("/api/admin/orbitfs/release-channels",{headers:await authHeaders(),cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load release channels");setData(j)}catch(e:any){setMsg(e.message||"Could not load release channels")}finally{setBusy("")}};
 useEffect(()=>{void load()},[]);
 const customers=useMemo(()=>new Map<string,any>((data.customers||[]).map((x:any)=>[String(x.id),x])),[data.customers]);
 async function mutate(body:any){setBusy(body.action||"save");setMsg("");try{const r=await fetch("/api/admin/orbitfs/release-channels",{method:"POST",headers:{"content-type":"application/json",...(await authHeaders())},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error||"Operation failed");setMsg("Saved.");await load()}catch(e:any){setMsg(e.message||"Operation failed")}finally{setBusy("")}}
 return <main className="lmPage">
  <div className="lmHero"><div><div className="lmEyebrow">ORBITFS · CUSTOMER DELIVERY</div><h1>Release Channels</h1><p>License Manager defines channel policy and technical entitlement state. Billing Store provides the customer/admin experience for join, request, approval, grant and revoke actions, all sent to License Manager. Stable remains the baseline channel for active customers.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><a className="buttonlink" href="/admin/orbitfs">OrbitFS Control</a><button onClick={()=>void load()} disabled={!!busy}>{busy==="load"?"Refreshing…":"Refresh"}</button></div></div>
  <section className="lmGrid2">
   <div className="lmCard"><div className="lmKicker">CHANNEL DEFINITIONS · LICENSE MANAGER</div><h2>Authoritative delivery channels</h2><p className="muted">These definitions are read-only here. Channel policy is owned by License Manager and mirrored into Billing Store for customer-facing flows.</p>{(data.channels||[]).length?(data.channels||[]).map((c:any)=><div className="lmRelease" key={c.id}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><b>{c.label}</b><span className={c.enabled!==false?"state ready":"state"}>{c.enabled!==false?"Enabled":"Disabled"}</span></div><small>{c.channel} · {c.customer_visible?"customer visible":"internal"} · {c.access_mode==="open"?"open":"assigned"}</small><p>{c.description||"No description."}</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}><span className="state">{c.access_request_enabled?"Requests allowed":"Requests off"}</span><span className="state">{c.self_join_enabled||c.access_mode==="open"?"Self-join allowed":"Self-join off"}</span></div></div>):<div className="lmEmpty">No channel definitions are available from License Manager.</div>}</div>
   <div className="lmCard"><div className="lmKicker">AUTHORITY</div><h2>Channel management boundary</h2><p className="muted">Billing Store does not create or redefine release channels. License Manager is the authority for channel definitions, access policy and technical entitlement state. Sync only refreshes the local compatibility mirror used by customer-facing Billing Store views.</p><button className="secondary" disabled={!!busy} onClick={()=>void mutate({action:"sync"})}>Sync from License Master</button></div>
  </section>
  <section className="lmCard" style={{marginTop:14}}><div className="lmKicker">ACCESS REQUESTS · LICENSE MASTER</div><h2>Pending customer requests</h2><p className="muted">Requests are stored and decided by License Master. Approving or rejecting here sends the decision back to License Master.</p>{(data.requests||[]).length?(data.requests||[]).map((r:any)=><div className="lmRelease" key={r.id}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><b>{r.channel}</b><small>{r.external_reference||r.license_id} · requested {r.requested_at?new Date(r.requested_at).toLocaleString():"—"}</small></div><div style={{display:"flex",gap:8}}><button className="primary" disabled={!!busy} onClick={()=>void mutate({action:"request",licenseId:r.license_id,channel:r.channel,userId:r.external_reference})}>Approve</button><button className="secondary" disabled={!!busy} onClick={()=>void mutate({action:"reject",licenseId:r.license_id,channel:r.channel})}>Reject</button></div></div></div>):<div className="lmEmpty">No pending channel access requests.</div>}</section>
  <section className="lmCard" style={{marginTop:14}}><div className="lmKicker">CUSTOMER ACCESS</div><h2>Who receives each channel</h2><p className="muted">Stable is always included. Granting Beta, Development or a custom channel adds that channel to the customer's release access; it does not remove Stable.</p>
   {(data.channels||[]).filter((c:any)=>c.enabled&&c.customer_visible).map((c:any)=><div className="lmRelease" key={c.id} style={{marginTop:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><b>{c.label}</b><small>{c.channel}{c.channel==="stable"?" · baseline":""}</small></div>{c.channel!=="stable"&&c.access_mode!=="open"&&<select className="input" style={{maxWidth:360}} defaultValue="" onChange={e=>{const userId=e.target.value;if(userId)void mutate({action:"grant",channel:c.channel,userId})}}><option value="">Grant access to customer…</option>{(data.customers||[]).map((u:any)=><option key={u.id} value={u.id}>{u.display_name||u.email||u.id}{u.company_name?" · "+u.company_name:""}</option>)}</select>}</div>
    {c.channel==="stable"?<p className="muted" style={{marginTop:8}}>Baseline: every active customer receives Stable automatically.</p>:c.access_mode==="open"?<p className="muted" style={{marginTop:8}}>Open channel: all active customers are eligible automatically.</p>:<>{(data.access||[]).filter((a:any)=>a.channel_id===c.id).map((a:any)=><div key={a.id} style={{display:"flex",justifyContent:"space-between",gap:10,marginTop:8,alignItems:"center"}}><span>{customers.get(a.user_id)?.display_name||customers.get(a.user_id)?.email||a.user_id}</span><button className="secondary" disabled={!!busy} onClick={()=>void mutate({action:"revoke",licenseId:a.license_id,channel:a.channel,userId:a.user_id})}>Revoke</button></div>)}{!(data.access||[]).some((a:any)=>a.channel_id===c.id)&&<p className="muted" style={{marginTop:8}}>No customers explicitly assigned.</p>}</>}
   </div>)}
  </section>
  {msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}
 </main>
}
