"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";

export default function LicenseMasterSettings(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 const [masterUrl,setMasterUrl]=useState("https://incendiarynetworks.cc/api"),[adminUrl,setAdminUrl]=useState("https://panel.incendiarynetworks.cc");
 async function headers():Promise<Record<string,string>>{const {data:{session}}=await createClient().auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{};}
 async function load(test=false){setBusy(true);setMsg("");setError("");try{const h=await headers();const r=await fetch("/api/admin/settings/license-master",{method:test?"POST":"GET",headers:{...h,...(test?{"Content-Type":"application/json"}:{})},body:test?JSON.stringify({}):undefined,cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"License Master request failed");setData(test?{...(data||{}),connection:{...(data?.connection||{}),last_success_at:new Date().toISOString(),last_error:null},connections:j.products?.map((p:any)=>({code:p.code||p.slug,master:p,local:null,connected:true}))||[]}:j);setMasterUrl(j.configuredUrl||j.connection?.master_url||masterUrl);setAdminUrl(j.masterPanelUrl||j.connection?.admin_url||adminUrl);if(test)setMsg(`License Master connected · ${j.latencyMs}ms · ${j.productCount} products`);}catch(e:any){setError(e?.message||"License Master unavailable")}finally{setBusy(false)}}
 async function save(){setBusy(true);setMsg("");setError("");try{const h=await headers();const r=await fetch("/api/admin/settings/license-master",{method:"POST",headers:{...h,"Content-Type":"application/json"},body:JSON.stringify({action:"save",masterUrl,adminUrl,enabled:true})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Could not save License Master settings");setEditing(false);setMsg("License Master settings saved.");await load(false);}catch(e:any){setError(e?.message||"Could not save settings")}finally{setBusy(false)}}
 useEffect(()=>{void load(false)},[]);
 const c=data?.connection,connections=Array.isArray(data?.connections)?data.connections:[];
 return <main className="adminShell settingsCompact">
  <header className="adminTop"><div><p className="eyebrow">MY ORBITFS · LICENSE MASTER</p><h1>License Master Connection</h1><p className="muted">Billing Store connects to the standalone License Master. License authority and validation remain in License Master.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="buttonlink secondary" href="/admin/licensing">License Master</Link><button className="buttonlink secondary" onClick={()=>setEditing(v=>!v)} disabled={busy}>{editing?"Cancel":"Edit connection"}</button><button className="buttonlink secondary" onClick={()=>load(true)} disabled={busy}>{busy?"Testing…":"Test connection"}</button></div></header>
  <section className="panel"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><h2>Connection</h2><p className="muted">Current default is <code>https://incendiarynetworks.cc/api</code>.</p></div>{editing&&<button className="buttonlink" onClick={save} disabled={busy}>{busy?"Saving…":"Save changes"}</button>}</div>
   <div className="form"><label>Master API<input value={masterUrl} onChange={e=>setMasterUrl(e.target.value)} readOnly={!editing}/></label><label>Master Admin<input readOnly value={adminUrl}/></label><label>Status<input readOnly value={c?.enabled!==false?(c?.last_error?"Error":"Connected"):"Disabled"}/></label><label>Last successful test<input readOnly value={c?.last_success_at?new Date(c.last_success_at).toLocaleString():"Not tested"}/></label><label>Last error<input readOnly value={c?.last_error||"None"}/></label></div>
  </section>
  <section className="panel"><h2>OrbitFS products</h2><p className="muted">Only these canonical products can be linked or validated through Billing Store.</p><div className="lmRuntimeList">{connections.map((x:any)=><div key={x.code}><div><b>{x.code}</b><span>{x.master?.name||"Not found in License Master"}</span></div><strong>{x.connected?"Connected":"Not connected"}</strong></div>)}{!connections.length&&<div><b>No product data</b><span>Test the License Master connection to load the canonical catalogue.</span></div>}</div></section>
  {msg&&<p className="inlineStatus">{msg}</p>}{error&&<p className="inlineStatus" style={{borderColor:"crimson"}}>{error}</p>}
 </main>;
}
