"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";

export default function LicenseMasterSettings(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 const [masterUrl,setMasterUrl]=useState("https://incendiarynetworks.cc/api/v1"),[adminUrl,setAdminUrl]=useState("https://panel.incendiarynetworks.cc");
 const [policy,setPolicy]=useState<any>({validation_ttl_seconds:60,offline_grace_seconds:0,pulse_poll_seconds:15,max_failed_validations:3,allow_offline_grace:false});
 async function headers():Promise<Record<string,string>>{const {data:{session}}=await createClient().auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{};}
 async function request(body?:any){const h=await headers();const r=await fetch("/api/admin/settings/license-master",{method:body?"POST":"GET",headers:{...h,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"License Master request failed");return j}
 async function load(test=false){setBusy(true);setMsg("");setError("");try{const j=test?await request({action:"test"}):await request();if(test){setMsg(`License Master connected · ${j.latencyMs}ms · ${j.productCount} products`);await load(false);return}setData(j);setMasterUrl(j.configuredUrl||j.connection?.master_url||masterUrl);setAdminUrl(j.masterPanelUrl||j.connection?.admin_url||adminUrl);if(j.pulse?.runtime_policy)setPolicy(j.pulse.runtime_policy)}catch(e:any){setError(e?.message||"License Master unavailable")}finally{setBusy(false)}}
 async function saveConnection(){setBusy(true);setMsg("");setError("");try{await request({action:"save",masterUrl,adminUrl,enabled:true});setEditing(false);setMsg("License Master connection saved.");await load(false)}catch(e:any){setError(e?.message||"Could not save settings")}finally{setBusy(false)}}
 async function savePolicy(){setBusy(true);setMsg("");setError("");try{await request({action:"configure",...policy});setMsg("Runtime validation policy saved in License Master and mirrored locally.");await load(false)}catch(e:any){setError(e?.message||"Could not save runtime policy")}finally{setBusy(false)}}
 async function sendPulse(){setBusy(true);setMsg("");setError("");try{await request({action:"pulse",reason:"billing-store-manual-validation-recheck"});setMsg("Pulse sent. Connected systems should invalidate cached validation and re-check enforcement.");await load(false)}catch(e:any){setError(e?.message||"Could not send pulse")}finally{setBusy(false)}}
 useEffect(()=>{void load(false)},[]);
 const c=data?.connection,connections=Array.isArray(data?.connections)?data.connections:[],pulse=data?.pulse||{},authority=pulse?.authority||{};
 return <main className="adminShell settingsCompact">
  <header className="adminTop"><div><p className="eyebrow">MY ORBITFS · LICENSE MASTER</p><h1>License Master Connection</h1><p className="muted">Billing Store is a client of the standalone License Master. Licensing authority, validation, grace policy and pulse state remain authoritative in License Master.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link className="buttonlink secondary" href="/admin/licensing">License Master</Link><button className="buttonlink secondary" onClick={()=>setEditing(v=>!v)} disabled={busy}>{editing?"Cancel":"Edit connection"}</button><button className="buttonlink secondary" onClick={()=>void load(true)} disabled={busy}>{busy?"Testing…":"Test connection"}</button></div></header>
  <section className="panel"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><h2>Connection</h2><p className="muted">All licensing operations use this configured <code>/api/v1</code> endpoint. Runtime validation no longer bypasses this setting.</p></div>{editing&&<button className="buttonlink" onClick={saveConnection} disabled={busy}>{busy?"Saving…":"Save changes"}</button>}</div>
   <div className="form"><label>Master API<input value={masterUrl} onChange={e=>setMasterUrl(e.target.value)} readOnly={!editing}/></label><label>Master Admin<input readOnly value={adminUrl}/></label><label>Status<input readOnly value={c?.enabled!==false?(c?.last_error?"Error":"Connected"):"Disabled"}/></label><label>Last successful test<input readOnly value={c?.last_success_at?new Date(c.last_success_at).toLocaleString():"Not tested"}/></label><label>Last error<input readOnly value={c?.last_error||"None"}/></label></div>
  </section>
  <section className="panel"><div className="panelTitle"><div><p className="eyebrow">AUTHORITATIVE STATE</p><h2>Master authority controls</h2><p className="muted">These values are read from License Manager, not duplicated in Billing Store.</p></div><span className={authority.system_enabled&&authority.licensing_enabled&&!authority.maintenance_mode?"state ready":"state waiting"}>{authority.system_enabled&&authority.licensing_enabled&&!authority.maintenance_mode?"ONLINE":"RESTRICTED"}</span></div>
   <div className="lmRuntimeList"><div><div><b>External authority</b><span>{authority.system_enabled?"External API authority is online.":"External API authority is disabled; runtime authority requests should fail closed."}</span></div><strong>{authority.system_enabled?"ON":"OFF"}</strong></div><div><div><b>License validation</b><span>{authority.licensing_enabled?"Runtime validation and issuance are enabled.":"License validation and issuance are disabled."}</span></div><strong>{authority.licensing_enabled?"ON":"OFF"}</strong></div><div><div><b>Maintenance</b><span>{authority.maintenance_mode?"Maintenance enforcement is active.":"Normal validation mode."}</span></div><strong>{authority.maintenance_mode?"ON":"OFF"}</strong></div></div>
  </section>
  <section className="panel"><div className="panelTitle"><div><p className="eyebrow">RUNTIME POLICY</p><h2>Validation, grace & pulse</h2><p className="muted">Saving here updates License Manager first. Billing Store only mirrors the values for local operational visibility.</p></div><span className="state ready">Pulse #{Number(pulse.pulse_revision||0)}</span></div>
   <div className="listrow"><div><b>Last pulse</b><span>{pulse.pulse_at?new Date(pulse.pulse_at).toLocaleString():"Never"} · {pulse.pulse_reason||"No reason recorded"}</span></div><button className="secondary" disabled={busy} onClick={()=>void sendPulse()}>{busy?"Working…":"Send pulse now"}</button></div>
   <div className="form">
    <label>Validation cache TTL (seconds)<input type="number" min="5" max="86400" value={policy.validation_ttl_seconds} onChange={e=>setPolicy((p:any)=>({...p,validation_ttl_seconds:Number(e.target.value)}))}/><small>Maximum age of a successful cached validation before a full recheck.</small></label>
    <label>Pulse poll interval (seconds)<input type="number" min="5" max="3600" value={policy.pulse_poll_seconds} onChange={e=>setPolicy((p:any)=>({...p,pulse_poll_seconds:Number(e.target.value)}))}/><small>How frequently connected runtimes should check for a newer pulse revision.</small></label>
    <label>Failed validations before local lock<input type="number" min="1" max="100" value={policy.max_failed_validations} onChange={e=>setPolicy((p:any)=>({...p,max_failed_validations:Number(e.target.value)}))}/><small>Runtime guidance for repeated validation failures.</small></label>
    <label style={{display:"flex",gap:10,alignItems:"center"}}><input type="checkbox" checked={!!policy.allow_offline_grace} onChange={e=>setPolicy((p:any)=>({...p,allow_offline_grace:e.target.checked,offline_grace_seconds:e.target.checked?p.offline_grace_seconds:0}))}/>Allow offline grace</label>
    <label>Offline grace (seconds)<input type="number" min="0" max="604800" disabled={!policy.allow_offline_grace} value={policy.offline_grace_seconds} onChange={e=>setPolicy((p:any)=>({...p,offline_grace_seconds:Number(e.target.value)}))}/><small>Temporary allowance only when the authority is unreachable. A new suspension/revocation pulse invalidates cached authorization once observed.</small></label>
   </div><button className="buttonlink" disabled={busy} onClick={()=>void savePolicy()}>{busy?"Saving…":"Save runtime policy"}</button>
  </section>
  <section className="panel"><h2>OrbitFS products</h2><p className="muted">Only these canonical products can be linked or validated through Billing Store.</p><div className="lmRuntimeList">{connections.map((x:any)=><div key={x.code}><div><b>{x.code}</b><span>{x.master?.name||"Not found in License Master"}</span></div><strong>{x.connected?"Connected":"Not connected"}</strong></div>)}{!connections.length&&<div><b>No product data</b><span>Test the License Master connection to load the canonical catalogue.</span></div>}</div></section>
  {msg&&<p className="inlineStatus">{msg}</p>}{error&&<p className="inlineStatus" style={{borderColor:"crimson"}}>{error}</p>}
 </main>;
}
