"use client";
import {useEffect,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";
export default function LicenseMasterSettings(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[masterUrl,setMasterUrl]=useState("https://incendiarynetworks.cc/api");
 async function headers(){const {data:{session}}=await createClient().auth.getSession();return session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{}}
 async function load(test=false){setBusy(true);setMsg("");try{const h=await headers();const r=await fetch("/api/admin/settings/license-master",{method:test?"POST":"GET",headers:{...h,"Content-Type":"application/json"},body:test?JSON.stringify({masterUrl}):undefined,cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"License Master request failed");setData(j);if(j.configuredUrl)setMasterUrl(j.configuredUrl);if(test)setMsg(`License Master connected · ${j.latencyMs}ms · ${j.productCount} products`);}catch(e:any){setMsg(e?.message||"License Master unavailable")}finally{setBusy(false)}}
 useEffect(()=>{void load(false)},[]);
 const c=data?.connection,connections=Array.isArray(data?.connections)?data.connections:[];
 return <main className="adminShell settingsCompact"><header className="adminTop"><div><p className="eyebrow">MY ORBITFS · LICENSE MASTER</p><h1>License Master Connection</h1><p className="muted">This is the Billing Store connection to the standalone License Master. License authority remains outside the Store.</p></div><div style={{display:"flex",gap:8}}><Link className="buttonlink secondary" href="/admin/licensing">License Master</Link><button className="buttonlink secondary" onClick={()=>load(true)} disabled={busy}>{busy?"Saving…":"Save & test"}</button></div></header>
 <section className="panel"><h2>Connection settings</h2><div className="form"><label>Master API<input value={masterUrl} onChange={e=>setMasterUrl(e.target.value)} placeholder="https://incendiarynetworks.cc/api" autoComplete="off"/><small className="muted">Locked to the production License Master origin. Legacy api.incendiarynetworks.cc is blocked.</small></label><label>Master Admin<input readOnly value={data?.masterPanelUrl||"https://panel.incendiarynetworks.cc"}/></label><label>Status<input readOnly value={c?.enabled!==false?(c?.last_error?"Error":"Connected"):"Disabled"}/></label><label>Last successful test<input readOnly value={c?.last_success_at?new Date(c.last_success_at).toLocaleString():"Not tested"}/></label><label>Last error<input readOnly value={c?.last_error||"None"}/></label></div></section>
 <section className="panel"><h2>OrbitFS products</h2><p className="muted">Canonical licence products are locked to License Master: orbitfs_base, orbitfs_mcp, orbitfs_apex, orbitfs_studio.</p><div className="lmRuntimeList">{connections.map((x:any)=><div key={x.code}><div><b>{x.code}</b><span>{x.master?.name||"Not found in License Master"}</span></div><strong>{x.connected?"Connected":"Not connected"}</strong></div>)}{!connections.length&&<div><b>No product data</b><span>Use Save & test to load the canonical catalogue.</span></div>}</div></section>
 {msg&&<p className="inlineStatus">{msg}</p>}</main>;
}