"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";
import Link from "next/link";

const BASE_REPO="lucaskerim123/V1-vercel-base";
const BASE_BRANCH="base-release";
const BASE_PRODUCT="orbitfs_base";

export default function AdminBaseDeployment(){
 const sb=useMemo(()=>createClient(),[]);
 const [releases,setReleases]=useState<any[]>([]),[version,setVersion]=useState(""),[commit,setCommit]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[changelog,setChangelog]=useState(""),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function request(path:string,method="GET",body?:any){const {data:{session}}=await sb.auth.getSession();if(!session?.access_token)throw Error("Administrator session expired.");const r=await fetch(`/api/admin/license-master?path=${encodeURIComponent(path)}`,{method,headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`License Master returned ${r.status}`);return j}
 async function load(){setBusy("load");try{const j=await request(`/api/releases?product=${encodeURIComponent(BASE_PRODUCT)}&channel=stable&type=base`);setReleases((j.releases||[]).sort((a:any,b:any)=>String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at))));setMsg("")}catch(e:any){setMsg(e.message||"Could not load Base releases.")}finally{setBusy("")}}
 useEffect(()=>{void load()},[]);
 async function capture(e:React.FormEvent){e.preventDefault();setMsg("");const sha=commit.trim();if(!/^[0-9a-f]{40}$/i.test(sha))return setMsg("The source commit must be the exact 40-character base-release commit SHA.");if(!version.trim())return setMsg("Version is required.");setBusy("capture");try{const j=await request("/api/releases","POST",{product:BASE_PRODUCT,version:version.trim(),release_type:"base",channel:"stable",source_repo:BASE_REPO,source_ref:BASE_BRANCH,source_sha:sha,notes:[description.trim(),changelog.trim()].filter(Boolean).join("\n\n")||title.trim()||null,artifact_url:null,vercel_ready:false,supabase_ready:false,customer_publication_repo:"lucaskerim123/V2_Billing_Store"});setMsg(`Base release ${j.release?.version||version.trim()} captured in License Master.`);setVersion("");setCommit("");setTitle("");setDescription("");setChangelog("");await load()}catch(e:any){setMsg(e.message||"Base release capture failed.")}finally{setBusy("")}}
 return <main className="lmPage">
  <div className="lmHero"><div><div className="lmEyebrow">MY ORBITFS · BASE RELEASE</div><h1>Base Deployment System</h1><p>Capture the exact OrbitFS Base release that is ready for publication. The standalone License Master owns the release record; this is the Billing Store staff control surface.</p></div><div className="lmHeroActions"><Link href="/admin/orbitfs">My OrbitFS</Link><Link href="/admin/orbitfs/update-release-deployer">Update Releaser</Link><button onClick={()=>void load()} disabled={busy!==""}>{busy==="load"?"Refreshing…":"Refresh"}</button></div></div>
  <div className="lmGrid2">
   <section className="lmCard"><div className="lmKicker">SOURCE</div><h2>OrbitFS Base</h2><div className="lmKV"><div><span>Repository</span><b>{BASE_REPO}</b></div><div><span>Release branch</span><b>{BASE_BRANCH}</b></div><div><span>Product</span><b>{BASE_PRODUCT}</b></div><div><span>Authority</span><b>Standalone License Master</b></div></div><p className="muted" style={{marginTop:14}}>The commit SHA is mandatory so the captured release points to an exact source revision.</p></section>
   <section className="lmCard"><div className="lmKicker">RELEASE FLOW</div><div className="lmRuntimeList"><div><b>1 · Ready</b><span>Base changes are merged to <code>{BASE_BRANCH}</code>.</span></div><div><b>2 · Capture</b><span>This screen creates the canonical base release in License Master.</span></div><div><b>3 · Review</b><span>Release operations remain in License Master and its authenticated API.</span></div><div><b>4 · Customer</b><span>Only a published base release becomes customer-available.</span></div></div></section>
  </div>
  <form className="lmCard" style={{marginTop:14}} onSubmit={capture}><div className="lmKicker">CAPTURE BASE RELEASE</div><h2>Capture exact source</h2><div className="lmGrid2"><label>Version<input value={version} onChange={e=>setVersion(e.target.value)} placeholder="e.g. 1.0.0" required /></label><label>Source commit SHA<input value={commit} onChange={e=>setCommit(e.target.value)} placeholder="40-character Git commit SHA" spellCheck={false} required /></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="OrbitFS Base 1.0.0" /></label><label>Description<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Release description" /></label></div><label style={{display:"block",marginTop:12}}>Changelog<textarea rows={5} value={changelog} onChange={e=>setChangelog(e.target.value)} placeholder="What changed in this Base release?" /></label><div className="actions" style={{marginTop:14}}><button className="primary" disabled={busy!==""}>{busy==="capture"?"Capturing…":"Capture Base Release"}</button></div>{msg&&<div className="lmNotice" style={{marginTop:14}}>{msg}</div>}</form>
  <section className="lmCard" style={{marginTop:14}}><div className="lmKicker">CAPTURED RELEASES</div><h2>Base release queue</h2>{releases.length?<div className="lmReleaseList">{releases.map((r:any)=><div className="lmRelease" key={r.id}><div><b>{r.version||r.id}</b><small>{r.status||"draft"} · {r.channel||"stable"}</small><p>{r.notes||"No release notes"}</p><small>Commit: {r.source_sha||r.source_commit||"not captured"}</small></div><span className={`state ${r.status==="published"?"ready":r.status==="disabled"?"error":"waiting"}`}>{r.status||"draft"}</span><div className="actions"><Link className="buttonlink" href="/admin/releases">Manage release</Link></div></div>)}</div>:<div className="lmEmpty">No Base releases are currently captured.</div>}</section>
 </main>
}
